import { SlashCommandBuilder, CommandInteraction } from 'discord.js';

module.exports = {
    data: new SlashCommandBuilder()
        .setName('rapiball')
        .setDescription('8ball, but its Rapi'),
    async execute(interaction: CommandInteraction) {
        const responses = [
            'Rapi says it is certain.',
            'Rapi is decidedly so.',
            'Rapi says without a doubt.',
            'Rapi says yes - definitely.',
            'Rapi says you may rely on it.',
            'Rapi says as I see it, yes.',
            'Rapi says most likely.',
            'Rapi says outlook good.',
            'Rapi says yes.',
            'Rapi says signs point to yes.',
            'Rapi says reply hazy, try again.',
            'Rapi says ask again later.',
            'Rapi says better not tell you now.',
            'Rapi says cannot predict now.',
            'Rapi says concentrate and ask again.',
            'Rapi says don\'t count on it.',
            'Rapi says my reply is no.',
            'Rapi says my sources say no.',
            'Rapi says outlook not so good.',
            'Rapi says very doubtful.',
            'Rapi says seggs = more child support',
            'Rapi says no, you cannot have seggs with Anis',
            'Rapi says Commander, that\'s classified information...',
            'Rapi says *yawns* too sleepy to answer now',
            'Rapi says this question needs tactical analysis',
            'Rapi says let me check the Outpost records first',
            'Rapi says that\'s above my clearance level',
            'Rapi says focus on the mission instead',
            'Rapi says ask me after maintenance',
            'Rapi says the Ark archives say yes',
            'Rapi says that\'s a negative, Commander',
            'Rapi says Commander... that\'s kind of weird...',
            'Rapi says maybe ask Shifty instead?',
            'Rapi says *looks at you suspiciously*',
            'Rapi says Commander, are you procrastinating again?',
            'Rapi says did you finish your dailies first?',
            'Rapi says *too busy gaming to answer*',
            'Rapi says Commander, please be serious...',
            'Rapi says *sighs* not this again Commander',
            'Rapi says have you checked the latest mission briefing?',
            'Rapi says let me consult with the squad first',
            'Rapi says that\'s a tactical error, Commander',
            'Rapi says Commander, shouldn\'t you be on patrol?',
            'Rapi says *checks her comms device*... No',
            'Rapi says that\'s not in the operation manual',
            'Rapi says let me check with HQ',
            'Rapi says the odds are in your favor.',
            'Rapi says I\'ll need more data for that.',
            'Rapi says the mission parameters are unclear.',
            'Rapi says I\'ll get back to you on that.',
            'Rapi says that\'s a strategic decision, Commander.',
            'Rapi says I\'m not authorized to disclose that.',
            'Rapi says let\'s keep our focus on the objective.',
            'Rapi says I\'ll need to run a diagnostic first.',
            'Rapi says that\'s a question for the higher-ups.',
            'Rapi says I\'ll need to consult the archives.',
            'Rapi says did you really just ask that?',
            'Rapi says maybe if you level up first.',
            'Rapi says I\'m not your personal guidebook.',
            'Rapi says try using your brain, Commander.',
            'Rapi says I\'m not a cheat code, you know.',
            'Rapi says maybe if you grind a bit more.',
            'Rapi says I\'m not here to hold your hand.',
            'Rapi says you might want to rethink that strategy.',
            'Rapi says I\'m not your in-game tutorial.',
            'Rapi says maybe you should read the manual.',
            'Rapi says Commander, are you sure you want to share Anis?',
            'Rapi says maybe you should focus on your own mission, Commander.',
            'Rapi says I heard Anis has been spending time with another Commander.',
            'Rapi says maybe you should ask Anis about her other Commanders.',
            'Rapi says Commander, are you feeling a bit left out?',
            'Rapi says maybe Neon is busy with someone else right now.',
            'Rapi says Commander, do you really want to know what Neon is up to?',
            'Rapi says maybe Neon has her own secrets to keep.',
            'Rapi says Commander, are you sure you can handle the truth about Neon?',
            'Rapi says maybe Neon is exploring other options.',
        ];
        const responseIndex = Math.floor(Math.random() * responses.length);
        const response = responses[responseIndex];
        await interaction.reply({
            content: `<:literawooo:1056600445558210632> ${response}`,
            ephemeral: false,
        });
    },
};
