module.exports = [
  "Which do you prefer: dogs or cats?\nAnswer : I'm more fond of cats.",
  "Is there anything I can do to help her out?\nAnswer : Just say 'Thank you.' She would appreciate that.",
  "When will she ever grow up?\nAnswer : It'd be better if you just gave up on that idea.",
  "What's your favorite place in the Outpost, Commander?\nAnswer : The courthouse, because it's where you are.",
  "Commander, what kind of weather do you like?\nAnswer : Rainy days.",
  "Are there times when that makes you feel sad, or even hateful toward us?\nAnswer : Never.",
  "Commander, do you have an ideal type?\nAnswer : Someone who is cute.",
  "Do you agree with that?\nAnswer : Eternal love does exist.",
  "Commander, where do you go when you want to relax and unwind?\nAnswer : A park without too many people.",
  "But... I'm not quite sure what kind of hobby to choose.\nAnswer : What about looking at cat pictures? Or taking cat pictures?",
  "What are your thoughts, Commander?\nAnswer : I can't give up, not until I know how it all ends.",
  "Any ideas?\nAnswer : Some alcohol.",
  "What type of music do you typically listen to, Commander?\nAnswer : Subdued and solemn music.",
  "Do you dream often?\nAnswer : No, not very often.",
  "If we manage to reclaim the surface, how would you feel?\nAnswer : I'd be elated.",
  "I tried it several times but can't seem to grab anything.\nAnswer : I'm the claw machine master.",
  "I've never tasted anything so sweet.\nAnswer : I've eaten a lot.",
  "Commander, out of curiosity, is there anything you would like as a gift?\nAnswer : Your time.",
  "I may have gone a bit overboard.\nAnswer : Not at all, as long as you finish reading all of them.",
  "How do they make that sound, I wonder?\nAnswer : Not as cute as your voice."
];