module.exports = [
    "Hiya, Rabbity! Where is the rabbit in this song going?\nIt's searching for a happier world.",
    "What if Sleeping Beauty gets hungry while she's sleeping?\nShe'll have plenty to feast on in her dreams",
    "Is there a way we can ask her to stop?\nWe could soothe her nerves with a cup of black tea.",
    "which taste do you prefer – sweet or salty?\n	I like salty-sweet carrots.",
    "What makes Splendamin so splendid?\nIt puts you in a splendid mood.",
    "what kind of weather do you prefer: sunny or snowy?\n	Snowy.",
    "I don't think I've ever seen them go to sleep, not even once.\nThat's why we have to make them all go to sleep.",
    "Oh! Rabbit! Do you always wake up this early?\nThat's right! I'm gonna go drink some spring water.",
    "I don't know what to do.\nThey will be fine as long as you stay with Ludmilla all the time.",
    "Remember?	OK.\nI will try my best in every race.",
    "Whenever you sleep, do you dream?\nAll the time.",
    "What do you like to do whenever it snows?\nHave a snowball fight.",
    "Rabbity, sing with me!\nAnswer :	Join in and complement her singing.",
    "What other animal friends are you close with?\nA dog.",
    "Have you ever eaten snow before?\nSure, I've eaten snow that's fallen on the ground.",
    "Do you like cotton candy, Rabbity?\nI like it because it's sweet.",
    "What goes through your mind when you can't fall asleep?\nI imagine tea time with you.",
    "What should I make them look like?\nLike a rabbit.",
    "Would a cloud melt like cotton candy do?\nSure, and it would probably taste the same as well.",
    "If you were the main character in a movie, what would you be?\nA hatmaker."
];