module.exports = [
    "Why do you keep staring at me?\n Because you look so powerful when you're by the sea.",
    "I thought it might be better to use a new nickname.\n Commander?",
    "Would you like to join us?\n Sure. I'll be on your team.",
    "But what should I photograph?\n The ocean.",
    "I'll give it up to her though, her aim is impressive.\n I got plastered with one as well.",
    "Are you a good swimmer, Subordinate?\n I could swim laps around you.",
    "If it is, what wish would you make, Subordinate?\n That we can one day reclaim the surface.",
    "Are you all right?\n I might have a mild bout of heatstroke.",
    "She said it looks great on me, so...\n I think it suits you well.",
    "I don't know what they're getting at when they say 'rest'.\n Maybe clearing your mind and thinking about nothing.",
    "What's your favorite fruit, Subordinate?\n If we're talking about summertime, peaches.",
    "Isn't it adorable?\n Looks a lot like you.",
    "It's so massive and majestic... just looking at it excites me.\n You look like you were meant to be on it.",
    "It feels like a ghost could pop up at any minute.\n 	... So. You think I'm human, huh?",
    "What do you think?\n Your uniform suits you better.",
    "It'd be a shame to spend the entire night here.\n Should we take an evening stroll?",
    "Helm stares at the beach as if in a reverie.\n ...",
    "what is the first thing you should do?\n Tell you.",
    "Preferably one that reaches the ankles.\n Let me see...",
    "Am I dreaming?\n Hold Helm's hand.",
];