module.exports = [
    "This is just part of everyday life for a cheerleader.\nI hope you didn't get hurt.",
    "What do you call when you stand on one leg and stretch your other leg out behind you?\nArabesque.",
    "What about you, Coach? What kind of weather do you like the most?\nSunny weather.",
    "What style do you think would suit me best?\nA hip street look.",
    "Someone who would help us put on a truly amazing performance.\nWhat about me?",
    "What do you recommend I have for dinner?\nA salad with chicken.",
    "What color do you think is best?\nPink. It goes well with the Rewind uniform.",
    "What kind of exercises do you think would be good?\nWalking.",
    "What song do you think would leave a strong impression?\nAn energetic pop song.",
    "I was wondering if you could recommend a particular scent that suits me?\nSomething sweet and sugary, like candy.",
    "Will I ever be able to overcome this crippling stage fright?\nYou can do this.",
    "How about you, Coach? Which of my beauty marks do you find most alluring?\nThey're all equally charming.",
    "I just want things to be more casual and easy. What should I do?\nIt'll resolve itself with time.",
    "Clay and I are going to watch a movie. What genre would be good?\nA high school film.",
    "Do you feel the same, Coach?\nHow could I possibly find time to eat a snack while watching you all perform?",
    "who cheers for us?\nI'll cheer for you.",
    "Coach, what do you think is the most important virtue a cheerleader should have?\nA genuine desire to cheer others on.",
    "When I arrive at the Commander's Room, I see Bay practicing in front of a doll.\nYou can do it!",
    "Do you have any foolproof methods to completely get rid of the smell?\nUse a detergent specially designed for sportswear.",
    "What kind of cheerleading style do you like best?\nThe explosive kind that involves a lot of energy."
];