module.exports = [
    "I just don't understand how someone can be injured so severely, without even knowing it.\n I'll be more careful next time.",
    "cold showers or hot showers more?\n Cold showers.",
    "What can I do to make her rest?\n I could fake an illness and lure her out of the clinic.",
    "in her swimsuit?\n I prefer a bit more of a mature vibe.",
    "I don't think it's that bad though. I wonder why?\n Maybe your wide-brim hat shields you from the sand?",
    "there are some things you shouldn't slack off on, don't you think?\n I've been having so much fun that I haven't had time to rest properly.",
    "Why is that?\n ... It's hard for me to talk about.",
    "Swimsuits, or my usual attire?\n Swimsuits, because of the novelty factor. We don't get to see you wearing something like this often.",
    "Commander, what kind of color do you think I like?\n Red.",
    "so I asked Neon to dig up a whole bunch of them for me. She got around 100!\n Neon could do this kind of stuff in her sleep.",
    "I'll give you a few hints: fever, headache, and chills.\n The flu.",
    "Don't you agree?\n Super cute. She follows you around like a puppy.",
    "What do you think of when you see the sunset, Commander?\n I feel a bit melancholy.",
    "Do you have any suggestions?\n How about putting up a warning sign that people won't miss?",
    "Have you been using the sunscreen I gave you?\n I can't reach my back, so I haven't been putting it on.",
    "What should I do to drive away those who aren't actually sick?\n Why not take the chance to give them a checkup?",
    "What do you do?\n Do a few warm-up stretches and enter the water.",
    "to beat the summer heat?\n You can't go wrong with a cool slice of refreshing watermelon.",
    "but what do you think of my swimsuit?\n It's sexy.",
    "You didn't hurt yourself, did you?\n Actually, I did take a tumble and swallowed a mouthful of salt water.",
];