module.exports = [
    "How would you feel if your close friend died?\n Mica will always be with you.",
    "what would you call us?\n Firecrackers",
    "What's on yours?\n To try new foods all around the world.",
    "What are you in the mood for?\n Setting off fireworks together.",
    "Do you like it?\n I'm a mint chocolate fanatic.",
    "Are you a good cook, Old-Timer?\n Cooking is a hobby for me.",
    "Are there any foods that you dislike?\n No.",
    "Do you prefer night or day?\n Night.",
    "Hey, how do you relieve stress?\n Eating something delicious.",
    "what would it be?\n Sustenance is paramount, so large quantities of canned food.",
    "They say the weather is gonna be beautiful tomorrow! What kind of things should I do?\n Play tricks on Mica.",
    "Breakfast, lunch, or dinner?\n The important thing is what you eat, not when you eat.",
    "What would you choose?\n A short life with no hunger.",
    "What do you even do on the holidays?\n Head out and have some fun.",
    "What kind of events should we hold?\n A two-for-one offer on tricks?",
    "or as a Rapture?\n Neither one is very scary.",
    "I should do something to put a smile back on her face. But what?\n Buy her something yummy.",
    "What kind of firecracker you think is better?\n Or those pretty ones that the Carronades like so much?",
    "Which one would you choose, Old-Timer?\n Apple.",
    "Who do you like better, me or Mica?\n You.",
];
