module.exports = [
  "Biscuit hands me a ball.\nAnswer : Thank you.",
  "Uh, isn't it... stifling to stay indoors today?\nAnswer : Shall we go out for a walk?",
  "W-Would you like to have some?\nAnswer : I'm good. You can have it all.",
  "Sweet snacks or savory snacks?\nAnswer : Sweet snacks are the best.",
  "Trainer, what kind of weather do you like?\nAnswer : Sunny weather.",
  "It makes me feel acknowledged, so I feel great!\nAnswer : Is that the so-called bond between dogs?",
  "She wags her tail furiously!\nAnswer : Stroke her head.",
  "Let's play together!\nAnswer : Lightly toss the frisbee toward the door.",
  "what kind of puppy would you want?\nAnswer : A puppy like you.",
  "Trainer, what kind of scent do you like?\nAnswer : The fresh smell of a dog right out of the shower.",
  "What should I do to overcome this?\nAnswer : Try covering your eyes as you speak.",
  "The same thing goes for other cats. Why are they so lovely?\nAnswer : Because they are born lovely.",
  "How about you, Trainer? Do you also want to understand them?\nAnswer : I do wish I can do that when they're sick.",
  "Uh... Trainer, what kind of person do you see me as?\nAnswer : A cool and mighty puppy.",
  "Hmmmmm...\nAnswer : Do you want some snacks?",
  "Do you like dogs or cats more?\nAnswer : Dogs.",
  "I hope they can be happy forever. Hehe.\nAnswer : They will be, since you're here.",
  "What should I do to give their teeth a good brush?\nAnswer : How about giving them snacks after brushing their teeth?",
  "Trainer... I'm hungry.\nAnswer : Give her sweet potato sticks.",
  "How can I get to know it better?\nAnswer : e patient and wait until it approaches you."
];