module.exports = [
    "what would thou do?\n I would spend time with the people that are precious to me.",
    "what course of action dost thou pursue?\n The only thing I can do is miss them.",
    "Dost thou consider us close?\n Of course, we're family.",
    "I held counsel with Rapunzel today about the joy of using one's body.\n What did you talk about?",
    "dost thou believe I am strong?\n Yeah.",
    "... That must be nice.\n Why don't you ask if you can join them?",
    "All I require is for thee to hold the object which I will be slicing.\n Oh boy!",
    "I long to tear apart a Rapture...\n ... I don't think it's possible for you.",
    "Pray tell, dost thou revel in the joy of drink?\n I don't understand the appeal spirits have for some people.",
    "...\n Don't you think the roses are beautiful?",
    "Do tell, are you proficient at organizing?\n No, I'm not.",
    "And yet, there is a remarkable sense of bonhomie amongst everyone here.\n You talk as if you're not part of the squad yourself.",
    "what virtue dost thou deem most important?\n Patience.",
    "there are times when I see myself in her.\n Because of her youth?",
    "It's floral tea.\n Thanks, I'd love a cup.",
    "Dost thou have any idea why this is?\n Of course, I do.",
    "yet shows no hint of weariness.\n It's just her nature.",
    "when will thou allow an official duel between Lilith and I?\n If I were to permit that, harm would befall you.",
    "...\n Throw a small branch at her.",
    "what dost thou believe is the reason behind my inability to best Dorothy?\n I believe it's due to a difference in experience.",
];