module.exports = [
    "what would it be?\n Hmm... Can you give me some time to think?",
    "I've got a date with Noir.\n Can you bring me with you?",
    "A or B?\n A.",
    "And I hate crying...\n Noir will always be with you.",
    "What's something on your bucket list, Pit Boss?\n To watch your show up on the surface.",
    "You'll come and watch, won't you?\n I'll be there, no matter what comes up.",
    "What exactly should I make?\n How about pictures of you?",
    "What would you like to do if you had a vacation, Pit Boss?\n Hang out with you.",
    "Blanc stares at me intently.\n Are you in love with me?",
    "what kind of outfit would be nice?\n You're perfect the way you look now.",
    "Would you be willing to try on my bunny ears?\n ... Sure, I guess.",
    "Pit Boss sounds so... old-fashioned at times.\n Call me by my real name.",
    "I want to do everything with her.\n What a great bond you two have.",
    "How do you think we should handle them?\n Let me take care of them.",
    "What's your favorite type of girl, Pit Boss?\n Someone vivacious.",
    "Any idea on how we can help her?\n You should hold her hand.",
    "What do you think?\n You're awfully pretty yourself, Blanc.",
    "It feels kinda lonely when I do it on my own.?\n If that's what you want, go for it.",
    "What do you think is the best way for me to transmit happiness?\n By holding hands.",
    "I can't get in touch with her either...\n Maybe she left to practice pole dancing.",
];
