module.exports = [
    "We got two kinds. Pick whichever one you want!\n I'll take the one that's a bit hairy.",
    "I wonder, what is its essence?\n I am waterpower, therefore waterpower is.",
    "have you got any in-depth knowledge to impart to me today?\n Sure, let's take a dip in the ocean.",
    "What could that mean?\n They're spies from Tetra. We should keep our eyes peeled.",
    "What does she do?\n Turn it on.",
    "my glasses will go flying and be swept away. What should I do?\n How about wearing goggles instead of glasses?",
    "That means I'll be the big cheese amongst the hybrids.\n I suppose so.",
    "I'm having a tough time figuring out which ones I like.\n Oh, there's one by your feet...",
    "I'd like to raise a dog of my own.\n Are you sure that you can handle that responsibility?",
    "for some summer activities I can do with Mary?\n Play games that test your courage in the dead of the night.",
    "That spot is shaded from the sun, and there's a nice breeze.\n If you stay there for too long, they'll give you a shot.",
    "If a shark and whale fought, who would win?\n The whale, of course.",
    "When you think of fun activities to do by the seaside, what comes to mind first?\n Adrenaline-pumping water sports where you zoom across the sea.",
    "What do you think of my swimsuit? Be honest.\n It's cute.",
    "I'm very talented at goofing off.\n All right, show me what you've got.",
    "Aren't hammocks meant to be used by everyone?\n I'll talk to her about it.",
    "Why is sea water so salty? It tastes awful.\n Why are you so hell-bent on drinking it?",
    "I almost fell for Yan's promotional tactics again!\n I'm impressed that you stood your ground.",
    "From now on, you're gonna be on easy street.\n So, in other words, you're an opportunist.",
    "Waterpower, waterpower! Waterpower!\n Waterpower!",
];