module.exports = [
    "She relies on others too much. It's a bad habit.\nIgnoring her won't fix that.",
    "Who made this?\nAnswer :	Bring her a coffee without saying anything.",
    "Or do you prefer a nutty flavor?\nAnswer :	Nutty.",
    "What can I do to discourage Diesel from singing without offending her?\nAnswer :	Tell her to fill her mouth with candy during her shift.",
    "Have you experienced any inconveniences?\nAnswer :	A few days ago, Soline was sitting beside me and grumbling.",
    "Do you agree, Commander?\nAnswer :	No. I believe it is perfect as it is.",
    "Or do you alternate between work and breaks to keep things in balance?\nAnswer :	I do it all at once.",
    "Are you working today, or will you be going out to have some fun?\nDo I have other options, aside from work?",
    "Now I wonder if I have given her too heavy a burden.\nAnswer :	Diesel is a strong leader.",
    "Commander, perhaps you know the reason?\nThe AZX is becoming more and more popular.",
    "or the future?\nThe past.",
    "or through text messages?\nText messages.",
    "when you look at me, what do you see?\nA workaholic.",
    "Don't you have something to say to me?\nAnswer :	Did you finish all your work?",
    "what would you want to do?	Day off?\nThere is no such thing.",
    "Is there anyone you're having difficulty working with?\nAnswer :	No one comes to mind.",
    "Do you believe there's such a thing as a white lie?\nNo, I don't.",
    "Or do you prefer to play it safe and not risk it?\nI prefer to play it safe.",
    "How do you feel about trains?\nI long for the day I can ride the rails up on the surface.",
    "where do you think I will be in 10 years?\nYou'll probably still be running the train like you are now."
];