module.exports = [
    "What should I do?\nMake it louder!",
    "Does all my noise make you uncomfortable?\nActually, it energizes me!",
    "I just can't make up my mind!\nIf you can't decide, just build two buildings!",
    "I'm terrified I'll run out of spots to build on before long!\nWe'll take back the surface soon!",
    "A building schedule is like a promise! I can't go around breaking my promises!\nA good builder does not blame their tools!",
    "This really bothers me!\nJust eat a day's worth of food at once!",
    "But she would kill me if I did!\nDon't worry! She wears a helmet!",
    "Can you pick one for me?\nA truck!",
    "What should I do?\nNo matter what, safety always comes first!",
    "I want to help them, but I don't know what to do!\nRebuild the whole Outer Rim!",
    "I'm struggling to find ways to get close to him!\nTake him out for walks every day!",
    "but I'm not sure what color I want to get.\nGrey.",
    "The dream was so vivid, I'm still replaying it in my mind!\nThat was no dream, that was a vision!",
    "I only have two hands, so I can't hold an umbrella.\nWear a raincoat while you're working.",
    "Soooo, I'm wondering what kind of music I should listen to while I work.\nCrank some hip-hop and hammer along to the beat.",
    "I'm worried I'll be useless without her.\nDon't worry too much about things that haven't even happened yet.",
    "Boss, what do you normally do during your free time?\nAnything to improve me.",
    "Or do you prefer places with fewer people around?\nCrowded places.",
    "The idea that my job might disappear one day really bums me out.\nI'm pretty sure our jobs are safe.",
    "There's got to be some way around this...\nWear shoes without laces."
];