module.exports = [
  "Do you know any place that's worth spending my money on?\nAnswer : Dark Net?",
  "Do you have the authority to get it taken off?\nAnswer : I will make the request to Syuen.",
  "I just can't figure out what it is.\nAnswer : Do you have any guesses?",
  "Any good tips for training a dog?\nAnswer : I will ask a Nikke who owns a dog.",
  "What's the difference between humans and Nikkes?\nAnswer : The possibility of duplication.",
  "Or would you just burn it?\nAnswer : I would wash it and reuse it.",
  "You ever been to the Outer Rim?\nAnswer : Yes.",
  "What do you think?\nAnswer : No, of course not.",
  "Any ideas?\nAnswer : I'll take you there.",
  "Can you guess why?\nAnswer : Because you enjoy breaking their ideals.",
  "how do you keep yourself from getting too anxious?\nAnswer : Tell them to hurry it up.",
  "Is there anyone you could never be close to?\nAnswer : Well... you, for one",
  "How can I set them straight?\nAnswer : Tell them specifically what they're doing wrong.",
  "What do you think of Syuen and Missilis?\nAnswer : ...",
  "I'm technically the leader of Heavenly Ascension.\nAnswer : Is that not correct?",
  "Hey commander what do you admire most in a person?\nAnswer : Firm beliefs.",
  "would you do it?\nAnswer : Yes.",
  "Any recommendations?\nAnswer : A dog toy.",
  "It's always bandied about like it's a given, but is it actually possible?\nAnswer : I doubt it will happen in my lifetime.",
  "Have you ever wanted something so badly, that you were willing to die for it?\nAnswer : Yes, the safety of the people."
];