module.exports = [
    "What do you think, Commander?\n We'd have never allowed such indolence back in my day.",
    "Could you please transmit a bugle call from the radio tower at approximately 6 AM?\n Private {AccountData.NickName}, reporting for duty!",
    "Do you think it's important how food tastes?\n No, it's not terribly important.",
    "Do you have any advice for me?\n Trust me.",
    "Hey Commander, how are you feeling?\n Great.",
    "If you received a compliment, what type of dance would you like to do?\n Popping and locking.",
    "if we fail to reclaim the surface and things merely remain as they are?\n I'd refuse to give up.",
    "What are you setting out to accomplish this year, Commander?\n Weapons research.",
    //TODO: This may be incorrect mistake on dotgg.gg. Seems like a duplicate but not sure. Gotta verify later. REF: https://dotgg.gg/nikke/advise
    "What are you setting out to accomplish this year, Commander?\n To reclaim the surface.",
    "What are you willing to invest your time and money into?\n Someone that piques my interest.",
    "Do you ever think about it, Commander?\n No. I live in the moment.",
    "How should I decline her offer?\n Think of it as team building.",
    "Could you recommend some music?\n Military anthems.",
    "What goes through your mind during battle?\n I'm thinking about how to save everyone.",
    "Is it funny to treat training as a hobby?\n Maybe they just thought your answer was unusual.",
    "Commander, do you have a type?\n I like people who work hard for themselves.",
    "What is the correct course of action?\n Take the effort you would have put into rest and put it into training.",
    "Spicy, or not spicy?\n In war, any food will do.",
    "I am worried that I have been too harsh when talking to Signal.\n You really should treat Signal better.",
    "Take this opportunity to get some rest and relaxation at the Outpost.\n I'm afraid not. No way I'm letting my guard down.",
];
