module.exports = [
    "Are you bored or something?\nYes.",
    "What should I do?\nGive her some better strawberry candy.",
    "What can I do to cheer her up?]nAnswer: Ask Soline to stay away from Brid for a while.",
    "Commander, do you like soft flavors or strong flavors?\nAnswer: Strong.",
    "AZX is coming through! Ding dong!\nAnswer: She's out of tune, but just let her sing.",
    "Commander, did you like Ark Rangers when you were a kid?\nAnswer: I was a huge fan.",
    "What should I do?\nAnswer: The AZX is already perfect. No need to decorate.",
    "what would you do, Commander?\nAnswer: Practice my singing.",
    "What would I be doing if I hadn't come to work at Arc Express?\nAnswer: Probably a pop idol.",
    "would you want to go back and change anything?\nAnswer: Yes.",
    "where would you go?\nAnswer: Somewhere near the ocean where I could hear the sound of crashing waves.",
    "What's your favorite color, Commander?\nAnswer: Blue.",
    "What type of clothing style do you like?\nAnswer: Cool and casual.",
    "Is there anything else I could get her to drink instead of coffee?\nAnswer: Make her a sweet strawberry latte.",
    "What's your favorite smell?\nAnswer: Sweet fruits,",
    "In your mind, what's the ultimate compliment?\nAnswer: Any compliment from you.",
    "What do you prefer?\nAnswer: Phone calls.",
    "What's something small that makes you happy?\nAnswer: Talking with you.",
    "Is there anything you would want as a birthday present?\nAnswer: Strawberry cake.",
    "What age do you want to live until?\nAnswer: I want to be immortal."
];