module.exports = [
    "Do you invest in stocks?\nAre there any good stocks to invest in?",
    "[The end justifies the means.] What do you think of this saying?\nI agree.",
    "Rupee is completely stupid, and Yan is pretty annoying.\nYet you still trust them.",
    "What's your ideal type?\nSomeone with ambition...",
    "Have you ever broken the law?\nHasn't everyone?",
    "What will I be in 10 years?\nThe CEO of a monopoly.",
    "How can people be content with the things they already have?\nWhat good is feeling satisfied, anyway?",
    "Any places you recommend?\nThe hot springs.",
    "Ah. Don't get me wrong. Just asking for market research.\nA smartwatch for everyday wear.",
    "*Sigh*\nDid something go wrong with a transaction?",
    "Tell me, how does it feel to never have the upper hand in any relationship you have with others?\nI consider it an investment that could potentially pay off big down the line.",
    "If you want, you could come to my office someday and we can look at it together.\nAnytime.",
    "does it stress you out? Or do you just ignore it?\nIt lights a fire underneath me.",
    "You don't know what he's into by any chance, do you?\nWhy? Do you need something from him?",
    "If you were to go with me, where would you go?\nTo Royal Road.",
    "What would you do? Hypothetically.\nDo what has to be done.",
    "What kind of excuse would you use?\nThere's still half left, so I wouldn't lose my head.",
    "I just want to rough him up a bit...\nWhat he did was unforgivable.",
    "Would you rather save your money, or invest it?\nInvest.",
    "How much money do you think it takes before you're satisfied?\nYou'll never be satisfied, no matter how much money you have."
];