module.exports = [
  "Do you invest in stocks?\nAnswer : Are there any good stocks to invest in?",
  "[The end justifies the means.] What do you think of this saying?\nAnswer : I agree.",
  "Rupee is completely stupid, and Yan is pretty annoying.\nAnswer : Yet you still trust them.",
  "What's your ideal type?\nAnswer : Someone with ambition...",
  "Have you ever broken the law?\nAnswer : Hasn't everyone?",
  "What will I be in 10 years?\nAnswer : The CEO of a monopoly.",
  "How can people be content with the things they already have?\nAnswer : What good is feeling satisfied, anyway?",
  "Any places you recommend?\nAnswer : The hot springs.",
  "Ah. Don't get me wrong. Just asking for market research.\nAnswer : A smartwatch for everyday wear.",
  "*Sigh*\nAnswer : Did something go wrong with a transaction?",
  "Tell me, how does it feel to never have the upper hand in any relationship you have with others?\nAnswer : I consider it an investment that could potentially pay off big down the line.",
  "If you want, you could come to my office someday and we can look at it together.\nAnswer : Anytime.",
  "does it stress you out? Or do you just ignore it?\nAnswer : It lights a fire underneath me.",
  "You don't know what he's into by any chance, do you?\nAnswer : Why? Do you need something from him?",
  "If you were to go with me, where would you go?\nAnswer : To Royal Road.",
  "What would you do? Hypothetically.\nAnswer : Do what has to be done.",
  "What kind of excuse would you use?\nAnswer : There's still half left, so I wouldn't lose my head.",
  "I just want to rough him up a bit...\nAnswer : What he did was unforgivable.",
  "Would you rather save your money, or invest it?\nAnswer : Invest.",
  "How much money do you think it takes before you're satisfied?\nAnswer : You'll never be satisfied, no matter how much money you have."
];