module.exports = [
  "I wonder why...?\nAnswer : Because they want you to have more.",
  "Commaaander! Are you free this weekend?\nAnswer : Of course.",
  "What's your favorite color, Commander?\nAnswer : Black.",
  "Is there anything I can do to help them?\nAnswer : They'll have to figure it out for themselves.",
  "But, I'm supposed to be the big sister!\nAnswer : That's just part of your charm.",
  "You look terrible. What's wrong?\nAnswer : I'm just overworked.",
  "just like some abomination from the depths of the ocean...\nAnswer : Open your mouth.",
  "I don't have time to go back and exchange it...\nAnswer : I can help.",
  "Why is that?\nAnswer : It's because you're so pretty.",
  "How can I get her to loosen up?\nAnswer : Use your special skills to help her calm down.",
  "Hmm... What should I do?\nAnswer : How about mixing it with something else?",
  "Bold, or understated?\nAnswer : Understated, with hints of boldness.",
  "Wait... could it be...\nAnswer : ... Maybe they're just feeling under the weather.",
  "Take a guess!\nAnswer : She probably tries her best not to make a sound.",
  "Nothing's been stressing me out... I'm not sure why I feel this way.\nAnswer : Sounds like it might be a physical issue.",
  "what do you think is the most important part of cooking?\nAnswer : Your mindset.",
  "Did you not sleep well? You look like you can barely keep your eyes open.\nAnswer : I stayed up all night thinking about you, Emma.",
  "do you usually take the lead? Or do you let the other person take charge?\nAnswer : I can do both. It all depends on who I'm with.",
  "However, that means there are times I pick up on things I'd rather not know.\nAnswer : That's a good skill to have.",
  "I'll see if I can make anything special for you.\nAnswer : Cake."
];