module.exports = [
  "What is your favorite flavor?\nAnswer : Peach.",
  "Got any tips?\nAnswer : Come to my office. I can help you.",
  "Am I... short?\nAnswer : The shorter, the cuter!",
  "Coach, do you ever get tired of being a Commander?\nAnswer : All the time.",
  "I have a big competition tomorrow at Nepenthe.\nAnswer : I'll be there. I promise.",
  "I wanna know what skateboarders were like back then.\nAnswer : Free as a bird.",
  "There's a park by the gym.\nAnswer : Sure.",
  "She says I can't have any carbs... and I have to take protein Splendamin four times a day.\nAnswer : That sounds like workplace bullying.",
  "I know they're just kids, but they need to learn to think for themselves, right?\nAnswer : Teenagers only copy the coolest people.",
  "Coach, have you ever... liked someone?\nAnswer : I'm still waiting.",
  "What do you usually do to pull yourself back up on your feet?\nAnswer : I face the problem head on until I overcome it.",
  "What do you normally carry in your pockets?\nAnswer : Some candy or gum.",
  "what's the first thing you would do?\nAnswer : Experience my first moment of freedom skateboarding with you up on the surface.",
  "What do you think I should call it?\nAnswer : First off, what's the trick?",
  "They're both the same brand.\nAnswer : One that's tricked out.",
  "I want to live up to those high expectations, so I always push things to the limit.\nAnswer : That mindset is what got you to where you are today.",
  "I know full well she'll smoke me, but I think it'd be fun, don't you?\nAnswer : It'll be a race for the ages.",
  "Coach, I need something right away. Can you guess what it is?\nAnswer : Shoes.",
  "You think I should tell Folkwang to give skateboarding a try?\nAnswer : I think it's a great idea.",
  "You think there's any way to counteract that problem?\nAnswer : Have everyone wear safety gear."
];