module.exports = [
  "I seek your advice on this.\nAnswer : Are you talking about me?",
  "But, what's wrong with stating simple facts?\nAnswer : Don't back down, no matter what other people say.",
  "Hey Noob, do you prefer 2D or 3D?\nAnswer : 2D, for sure.",
  "How should I resolve the situation?\nAnswer : Get noise canceling headphones.",
  "However, I do not enjoy seeing people offline. Please propose a solution.\nAnswer : I can go with you, if you like.",
  "I think I may be becoming desensitized to games.\nAnswer : You'll feel better after a day or two.",
  "What is the optimal course of action?\nAnswer : Tell them about it and say you're sorry for snooping.",
  "You are the one who is in control here. I require your assistance. Please!\nAnswer : You can use the shower in my room.",
  "I require a means of escape, of release.\nAnswer : Let's run away together.",
  "I would like to hack Enikk's mainframe.\nAnswer : If you want it that badly, just go for it.",
  "Anyway, is there anything you wanted to ask me?\nAnswer : What's the attack pattern for the raid boss in chapter 3?",
  "Helloooooo? Anyone there?\nAnswer : Request a PVP with them.",
  "She makes such a racket, I can't concentrate on my games!\nAnswer : Have her go to a gym instead of the house.",
  "What kind of concept do you think would suit me?\nAnswer : A detective otaku who is crazy about mystery.",
  "There's a bug in the game that prevented me from clearing this mission.\nAnswer : Try and debug the game yourself.",
  "during a team PVP match?\nAnswer : Carry the team on your back.",
  "If the world were going to end tomorrow, what would you do?\nAnswer : I would complete more side missions in this game I'm playing.",
  "What do you think I should do?\nAnswer : I'd consider being more strategic.",
  "Exia is focused on playing a game.\nAnswer : Turn on the same game.",
  "Just who exactly are you?\nAnswer : I don't remember. You have to help me remember my identity."
];