module.exports = [
  "Coach, how can I keep myself from getting too hot?\nAnswer : Would hugging me help?",
  "Do you have any idea why?\nAnswer : She just doesn't like ice supplements.",
  "I don't think it makes our lives better at all.\nAnswer : Your body sweats just to give you a hard time.",
  "would you turn the air conditioner on or off?\nAnswer : I think turning it on would be right.",
  "Coach, what kind of weather do you like the most?\nAnswer : Cloudy days.",
  "where will you go?\nAnswer : The swimming pool.",
  "If they do, it'd really hurt my feelings.\nAnswer : No, of course not. They don't hate sweaty people...",
  "But, I'm even older than she is!\nAnswer : Then try to be more understanding of her, since you are older.",
  "What do you think, Coach?\nAnswer : Running is the best.",
  "Soda ice Splendamin is my favorite!\nAnswer : Want me to get you some?",
  "There's a word to describe this, what was it called again?\nAnswer : Runner's high.",
  "I'm going to quit being an athlete and become a doctor.\nAnswer : Is that just because you'll have plenty of nurses around to wipe off your sweat?",
  "Do you think it'd be all right if I said hi to her?\nAnswer : Sure, go for it.",
  "If you took more than the recommended amount, wouldn't they be even more effective?\nAnswer : I think you may be onto something.",
  "is slap maxi pads all over my body!\nAnswer : Won't that weigh you down?",
  "it might make the people around me feel uncomfortable...\nAnswer : It's okay, because your sweat actually smells quite nice.",
  "Do you know any methods to deal with this?\nAnswer : Let's try finding a supplement that makes you enjoy combat.",
  "It got me thinking... why exactly do I prefer it?\nAnswer : With running, you can gain momentum without any outside assistance.",
  "I'll recommend you a good one.\nAnswer : I'm already taking some.",
  "Call it what you will, but I call it abuse.\nAnswer : She's just doing her best to help you."
];