module.exports = [
  "Tired now. Sleep.\nAnswer : You're tired because you sleep too much.",
  "Which?\nAnswer : Sandwich.",
  "More?\nAnswer : Keep it coming until there's more cream than coffee.",
  "Instead?\nAnswer : You need to do your own work.",
  "Want... nice place.\nAnswer : Just sleep here.",
  "Annoyed.\nAnswer : But you'd be bored without them.",
  "Bothersome.\nAnswer : But you'll do it because you enjoy it, right?",
  "Music. Recommend?\nAnswer : No music. Noise canceling headphones instead.",
  "Good? Bad?\nAnswer : I'm not sure. I think you look kinda cute when you're asleep.",
  "Nightmare. Terrible.\nAnswer : But you could sleep on literally anything, right?",
  "Don't understand.\nAnswer : I'm sure Cream Coffee will sell better next week.",
  "How to use?\nAnswer : They'll go towards renovating some facilities in the Outpost.",
  "What now?\nAnswer : Try counting sheep.",
  "Difficult. Annoying.\nAnswer : Let them have it next time.",
  "Why?\nAnswer : It's because of the economic recession.",
  "Boss. Scary.\nAnswer : Bothersome?",
  "How?\nAnswer : Sleep more and cut back on your spending.",
  "...\nAnswer : Do you not want to talk since you don't feel well?",
  "Raining. Can do what?\nAnswer : Head back to bed.",
  "Which?\nAnswer : A nice and soft sofa is the only way to go."
];