module.exports = [
  "who do you think is the nicest?\nAnswer : You.",
  "How can I get people to hear me out?\nAnswer : Speak with more conviction.",
  "Guilty clenches onto my hand more tightly.\nAnswer : Grip even tighter.",
  "Do you ever lie, Counselor?\nAnswer : Sometimes, and I'm pretty good at it.",
  "They're so annoying...\nAnswer : Remove her restraints for a moment.",
  "Didn't you say I was already rehabilitated?\nAnswer : I came because I wanted to spend time with you, that's all.",
  "I wonder, what kind of hobby should I pursue?\nAnswer : Going for a walk while handing hands?",
  "When are you the happiest, Counselor?\nAnswer : When I'm with you.",
  "How do you get rid of stress?\nAnswer : I exercise.",
  "What should I do?\nAnswer : Want me to hold your hand while you sleep?",
  "I always use voice-to-text, so I can't help that it's slow sometimes...\nAnswer : Don't worry about Sin. She's in the wrong.",
  "Hurting someone physically, or hurting their feelings?\nAnswer : Hurting someone's feelings.",
  "Why am I under more heavy restraints than they are?\nAnswer : Because the crimes you committed were more serious.",
  "What do you think I did when that happened?\nAnswer : You ignored them.",
  "or do you prefer being hugged?\nAnswer : I like giving hugs.",
  "My hands...\nAnswer : Are you asking me to untie your hands?",
  "can you pass me the water bottle that's over there?\nAnswer : Put a straw in the water bottle.",
  "So she left a bottle of hand lotion on the table to torment me with.\nAnswer : Relax. I'll put it on for you.",
  "Just once, pretty please?\nAnswer : Maybe next time... if we have a chance.",
  "Is there any truth to that?\nAnswer : Yeah, it's delicious."
];