module.exports = [
    "who do you think is the nicest?\nYou.",
    "How can I get people to hear me out?\nSpeak with more conviction.",
    "Guilty clenches onto my hand more tightly.\nGrip even tighter.",
    "Do you ever lie, Counselor?\nSometimes, and I'm pretty good at it.",
    "They're so annoying...\nRemove her restraints for a moment.",
    "Didn't you say I was already rehabilitated?\nI came because I wanted to spend time with you, that's all.",
    "I wonder, what kind of hobby should I pursue?\nGoing for a walk while handing hands?",
    "When are you the happiest, Counselor?\nWhen I'm with you.",
    "How do you get rid of stress?\nI exercise.",
    "What should I do?\nWant me to hold your hand while you sleep?",
    "I always use voice-to-text, so I can't help that it's slow sometimes...\nDon't worry about Sin. She's in the wrong.",
    "Hurting someone physically, or hurting their feelings?\nHurting someone's feelings.",
    "Why am I under more heavy restraints than they are?\nBecause the crimes you committed were more serious.",
    "What do you think I did when that happened?\nYou ignored them.",
    "or do you prefer being hugged?\nI like giving hugs.",
    "My hands...\nAre you asking me to untie your hands?",
    "can you pass me the water bottle that's over there?\nPut a straw in the water bottle.",
    "So she left a bottle of hand lotion on the table to torment me with.\nRelax. I'll put it on for you.",
    "Just once, pretty please?\nMaybe next time... if we have a chance.",
    "Is there any truth to that?\nYeah, it's delicious."
];