module.exports = [
  "Don't you think so?\nAnswer : It's almost as if... the wind is weeping.",
  "*Tee hee hee!*\nAnswer : Why are you laughing?",
  "How... do you control this feeling?\nAnswer : Embrace it. It is what we must do.",
  "They may very well be eavesdropping on this very conversation.\nAnswer : This place is safe. We're protected by the Aegis Barriers.",
  "Should I block followers who have private accounts?\nAnswer : No. If you did that, none of our allies with hidden identities could contact you.",
  "My right eye is tingling.\nAnswer : Could it be that the One-Winged Dark Lord's seal has been weakened?",
  "Can you even begin to comprehend my loneliness?\nAnswer : Yes, I do. I'm the only one who does.",
  "Could... she be afraid of the kotodama in my words?\nAnswer : She is not ready to accept your presence.",
  "What's she up to?\nAnswer : She just thinks your posts are fun to read, that's all.",
  "Someone who stays with you for the rest of your life?\nAnswer : That would make me very happy.",
  "Something doesn't feel right.\nAnswer : It's simply the energy emanating from the Dragon of the Deep.",
  "How can I find solace from their judgment?\nAnswer : It's too late for us to escape.",
  "What is happening?\nAnswer : Someone is sending you a signal from another dimension.",
  "What kind of music do you listen to when you're on your own?\nAnswer : Hymn of the Blood Moon.",
  "who do you think I am?\nAnswer : My partner in crime.",
  "Just let me be.\nAnswer : I won't let you suffer all alone!",
  "how would you spend your last day?\nAnswer : I'd spend it with you.",
  "which one would get the ax?\nAnswer : Day is on the chopping block.",
  "Do you think it's all right to lift the seal for a moment?\nAnswer : Not here!",
  "Can I hide here momentarily?\nAnswer : Sure."
];