module.exports = [
  "Tell me. What would you do if I blasted that crow out of the sky?\nAnswer : I'd go pick up the pear.",
  "Or does the thought of the sky caving in at any moment fill you with terror?\nAnswer : ...",
  "What would you have me do?\nAnswer : You're an adult, so you should rise above all this and forgive her.",
  "Tell me, what is it about you that has made her like this?\nAnswer : My charming personality?",
  "How is it, working for them? Any fun?\nAnswer : It's a real drag.",
  "Are you happy being here?\nAnswer : I am not.",
  "Do you agree that I am the most important thing in the world?\nAnswer : I do.",
  "What flavor do you think I would like?\nAnswer : Nothing could satisfy you.",
  "can compare to mine?\nAnswer : No.",
  "How did you feel?\nAnswer : I was happy.",
  "Wait, is there even such a thing as the weather in that dismal hole you call a city?\nAnswer : ...",
  "and betray one another?\nAnswer : Not everyone is that way.",
  "who is the fairest of them all?\nAnswer : You.",
  "Would you like me to make some witch's brew?\nAnswer : Yes, please.",
  "Well, what do you think? Am I more captivating now?\nAnswer : You've always been endlessly alluring, Harran.",
  "Don't you agree?\nAnswer : I'm not sure.",
  "Do you think we'll ever see the day where there are no Raptures on the surface?\nAnswer : I believe we will.",
  "Have you ever wanted to go back to the past?\nAnswer : For me, the past should remain in the past.",
  "Do you prefer red or blue?\nAnswer : Red.",
  "who do you think makes a better follower?\nAnswer : Of course it's me."
];