module.exports = [
  "Tried-and-true tactics or improvisation?\nAnswer : Tried-and-true tactics.",
  "Octopus-flavored Splendamin. Halibut-flavored Splendamin. Things like that...\nAnswer : Not really.",
  "Just so you know, I'm not a massive fan of any of them.\nAnswer : Spicy.",
  "the surface will be reclaimed one day?\nAnswer : Yes, I believe it will happen.",
  "how do you intend to spend it?\nAnswer : I'll invest in the Admire.",
  "It's been ages since I last got in touch with her, so I'd like to give her a gift. So what do you think I should give her?\nAnswer : A fancy tea set.",
  "I'm trying to get her to kick the habit, but I'm not sure how to go about it.\nAnswer : I'll toss out all the starfish in Anchor's locker.",
  "Argh, I can't memorize all this!\nAnswer : Would it help if I listened to you reciting the speech?",
  "All I could find was a lone glass box left on the floor.\nAnswer : Place a card containing small amounts of credit in the box.",
  "I'm only asking, just in case.\nAnswer : I'm extremely good at it.",
  "I haven't made any major blunders yet, but I'm worried it'll happen one of these days.\nAnswer : Don't forget who you're representing.",
  "So the question now is, what is the first thing you should do?\nAnswer : There's no way you'd ever fall into the water.",
  "Don't ask me why, but all it ever does is float in a swimming pool.\nAnswer : I mean, people become dirty too if they don't clean themselves up.",
  "It's not a st-starfish, is it?\nAnswer : That's a living, breathing starfish, all right.",
  "or a strong but slow ship?\nAnswer : A strong but slow ship.",
  "What will you do, Subordinate?\nAnswer : It'd be meaningless if I didn't accomplish it myself.",
  "For example, let's say... drinking on the job or throwing starfish.\nAnswer : I'd join them.",
  "I can't just leave it behind, though. So I don't know what to do.\nAnswer : It's not like you can explain the situation to each and every single person you meet.",
  "I don't mind people using the pool, but they should clean up after themselves.\nAnswer : I'll make sure it's cleaned from here on out.",
  "or something we should beseech everyone to do, regardless?\nAnswer : Fighting for a just cause should be respected, no matter what form it takes."
];