module.exports = [
    "Kind of like me with crafting weapons.\n Honestly, I'm a big fan of times like these. What we're doing right now.",
    "She is sleeping.\n Wake her up by poking her cheek.",
    "Would you like to share this potato?\n I'm good. It's all yours.",
    "I dream that everyone has disappeared and I've been left all alone.\n How about I sleep next to you tonight?",
    "Sunny or cloudy?\n I actually prefer snowy days.",
    "They're always at each others' throats whenever they're in the same room.\n Maybe that's just their way of showing affection.",
    "Commander, do you cherish old stuff of yours more?\n They do have their own unique charm.",
    "what do you intend to do there?\n I suppose I'd go on an outing with all of you.",
    "What do you usually do when you've got some time to rest, Commander?\n I take a rest, literally.",
    "and I can make it for you.\n I don't need anything as long as I have you protecting me.",
    "They had another squabble today and made a total mess of the barracks.\n Okay, I'll tell them to behave.",
    "That way, I'll be able to get back at Red Hood whenever she teases me.\n I don't think being mature has anything to do with it.",
    "What's going on with her?\n She's attempting mightily to be reborn as a true saint, so she needs all the help you can give her.",
    "Do you get the same feeling, Commander?\n Yeah, she can be a bit standoffish.",
    "Sometimes, it looks as though it has a life of its own.\n Perhaps because she wields it with such passion.",
    "Is that true?\n Not at all.",
    "why does Red Hood always make fun of me?\n Because she considers you a good friend.",
    "Oh, this?\n Share snack with Snow White.",
    "how can I become as strong as Lilith?\n That's something you must figure out for yourself.",
    "...\n Cool weapon.",
];