module.exports = [
  "...\nAnswer : Is there something on my face?",
  "Maybe it's that there are so many women around you all the time?\nAnswer : My relationship with them is strictly professional, nothing more.",
  "Why would they do that to me?\nAnswer : Could just be their personality.",
  "have I done something to upset you?\nAnswer : No.",
  "If only there was one more of you, I could hide the other you in a safe, secret place and love you forever.\nAnswer : Who knows what the future holds?",
  "I can't stand it when she's rude to you!\nAnswer : It doesn't bother me.",
  "don't you feel stifled, living underground?\nAnswer : Sometimes I feel like I'm going to explode.",
  "What... do you think about marriage?\nAnswer : It's two people intertwining into one.",
  "Tell me something about you. Anything.\nAnswer : There's nothing I love more than a blue sky.",
  "What do you think it would be like... to have a family?nAnswer : You'd feel like you have others to protect.",
  "Come here and I'll give you a hug.\nAnswer : ...",
  "With you, on a day like this...\nAnswer : Want to go on a trip?",
  "Have a little sip!\nAnswer : Take a sip.",
  "who would you want to be with?\nAnswer : Um... You?",
  "or something cozy with lots of woodwork?\nAnswer : Cozy and with lots of woodwork.",
  "what do you look for in your significant other?\nAnswer : You check all the boxes.",
  "Do you agree with that sentiment?\nAnswer : I don't.",
  "How was work?\nAnswer : Honey, I'm home!",
  "Do you think there will be a day when there are no more Raptures on the surface?\nAnswer : The day will surely come.",
  "What do you like doing during your spare time?\nAnswer : Sleeping."
];