module.exports = [
  "I'm in the mood for meat.\nAnswer : Let's have lamb-flavored Nutrium.",
  "Everything shatters into a million pieces! It's the coolest.\nAnswer : Just make sure you don't shoot at people.",
  "This has never happened before, it's weird.\nAnswer : You didn't bite down on a stone by any chance, did you?",
  "What's the big deal? I was so scared I ended up having to run away.\nAnswer : They just wanted to give you a hard time.",
  "What did I ever do to them?\nAnswer : It's impossible to be liked by everyone.",
  "Why's he so mad at me?\nAnswer : Imagine if Crow got beat up by someone.",
  "That's why she commands respect from everyone, including me.\nAnswer : What about me?",
  "I came by this yesterday, and it's not half bad.\nAnswer : Sure, but I'll melt it down first.",
  "Got any bright ideas on how I can get around it?\nAnswer : Let's practice jumping over it.",
  "Why doesn't she let me do what I want?\nAnswer : The hideout is much too small for you to run around in.",
  "Cmndr?\nAnswer : Still can't make out what you're saying, but... thanks?",
  "10 times. No! 100 times!\nAnswer : How does 1,000 times sound?",
  "Why would they name me after an animal?\nAnswer : Because you like meat?",
  "Got any good prank ideas?\nAnswer : Just lay low and keep quiet.",
  "I want to try it too!\nAnswer : How about getting your teeth treated?",
  "What should I do to make him fess up?\nAnswer : Maybe he really doesn't know anything.",
  "So I'm curious: is money really that important?\nAnswer : It's not that important.",
  "I'm gonna take it off.\nAnswer : Don't take it off. It looks good on you.",
  "I don't know why everyone else is so down on it.\nAnswer : They're just jealous.",
  "I don't get it. Books or movies don't fill your stomach, so what's the point?\nAnswer : She probably thinks it makes her look cool."
];