module.exports = [
  "I'm just not sure how to satisfy her desire.\nAnswer : Fire a gun.",
  "Which type of music are you in the mood for today?\nAnswer : Fast as a wave.",
  "Could... could Anis have seen my soul wandering around without me knowing?\nAnswer : I do think Anis has the power to see other people's souls.",
  "However, I don't know what kind of music to prepare.\nAnswer : Buoyant and entertaining music that will liven up the room.",
  "But... where?\nAnswer : Whenever you get musical inspiration?",
  "When it's raining, what kind of music do you like to listen to?\nAnswer : Bold, emotional music that washes over me like a downpour.",
  "What kind of music can best express my gratitude?\nAnswer : Something solemn that matches Rapi's style.",
  "When I feel this way, what should I do?\nAnswer : Use your music to express yourself.",
  "When you think of your hometown, what kind of music comes to mind?\nAnswer : Music that's full of nostalgia, with a tinge of warmth.",
  "I wonder what it could have been?\nAnswer : A marching song that instills bravery into even the most cowardly of soldiers.",
  "Julia is performing as if deeply immersed in her music.\nAnswer : Let her be.",
  "Should I play something soothing for you?\nAnswer : Actually, I'd prefer something more upbeat. I want to beat my fatigue into submission.",
  "When you are resting, what kind of music do you listen to?\nAnswer : Music that gives me nice dreams.",
  "If you could make today a holiday, what would you have it commemorate?\nAnswer : The moment I heard you play your music.",
  "Is there anything else I could try riding?\nAnswer : You could ride the rhythm.",
  "I wonder how much more they'll change in the future?\nAnswer : No matter how much things change, you'll always be who you are.",
  "Is that true?\nAnswer : It's a truly lonely and desolate place.",
  "That got me thinking: Is there anyone that you just don't get along with?\nAnswer : Not in particular.",
  "It was just awful! I can't get it out of my mind.\nAnswer : But even in a nightmare, you never forgot how to play your music, right?",
  "what would you do with it?\nAnswer : I would have you perform it for me."
];