module.exports = [
  "What do you think is the most important when it comes to being a hero?\nAnswer : Your mind, and your physical strength.",
  "Tah-dah! Here I am!\nAnswer : You're late.",
  "What would you do?\nAnswer : I'd call you immediately.",
  ".........\nAnswer : Have you not eaten?",
  "Why do you think that is? We're heroes after all...\nAnswer : She doesn't want to be an ordinary hero.",
  "a hero can't overcome?\nAnswer : Nothing whatsoever.",
  "But if I don't yell, I can't unleash my full power...\nAnswer : Use more body language and do all your yelling internally.",
  "what would it be?\nAnswer : World peace.",
  "That's what Nikkes were made to do, and it's what heroes were meant to do.\nAnswer : I'm with you all the way.",
  "Hero power, charging...\nAnswer : GO!!!!",
  "What would you do?\nAnswer : I'd get a drink of water to calm my nerves.",
  "Don't hold back. I won't get offended.\nAnswer : The fact that you have no shortcomings is your shortcoming.",
  "I can't help feeling regretful... What if I had more power then?\nAnswer : What difference would that make?",
  "for an entire hour.\nAnswer : That's a bit overkill.",
  "What do you think that's all about?\nAnswer : It means someone is accusing you of being a killer.",
  "Personally, I'm partial to beam-based weapons.\nAnswer : No contest. A beam weapon comes out on top.",
  "If you were my enemy, what would you do?\nAnswer : I'd want a fair fight. I'd wait until you had fully transformed before fighting.",
  "Birdie! Tell me what you think!\nAnswer : No, they can't.",
  "I need a unique entrance that's still a good fit for me.\nAnswer : Transform as you walk slowly.",
  "What do you think it means to be a hero?\nAnswer : Running towards what everyone else runs away from."
];