module.exports = [
  "Can nothing be done about this?\nAnswer : Let me do the work for you.",
  "Then again, as her guardian, perhaps I am just being selfish.\nAnswer : Even if she has to grow up, Alice will always be Alice.",
  "Is there anything I could do to make you more comfortable?\nAnswer : Any chance I could get a hug from you?",
  "Perhaps my taste buds are beginning to age?\nAnswer : Maybe it's the tea leaves that got old.",
  "What should I get for her?\nAnswer : A doggie bone made of ice?",
  "Do you have a type?\nAnswer : Someone who carries themselves like a Queen.",
  "Speaking of, have you ever been to Royal Road?\nAnswer : I haven't.",
  "How would you define family?\nAnswer : Similar to the relationship between you and Alice.",
  "Did you already know this?\nAnswer : I'd rather have the affection of someone else.",
  "What about you? Do you think living here is difficult?\nAnswer : It has its own stark beauty.",
  "What do you think of it?\nAnswer : It's far from heaven, that much is certain.",
  "What should I try?\nAnswer : Some bitter tea.",
  "What do you usually do on days like today?\nAnswer : It'd be nice to go out and have some tea.",
  "When you look at snow, what does it make you think of?\nAnswer : You.",
  "Which one do you think is better?\nAnswer : Real but dangerous.",
  "Why are you going to so much trouble to listen to all of our concerns?\nAnswer : You're all my friends and squadmates. I want to know what's on your mind.",
  "!!\nAnswer : Snatch the phone and ask what she is trying to do.",
  "called people, or sent them messages?\nAnswer : Calling.",
  "Looking back, are there any locations that stand out?\nAnswer : For one, I remember the snowfields up north, where I met you.",
  "Would you like to try it?\nAnswer : Sure, why not."
];