module.exports = [
  "Or do you prefer it salty?\nAnswer : Both.",
  "... or be just a little sick for a long time?\nAnswer : Option 1.",
  "Even the bad ones?\nAnswer : No.",
  "What should I do?\nAnswer : Give them a painful shot.",
  "Every time I see Pepper, I just get so excited!\nAnswer : Let me guess. You've found something to tease her about.",
  "How should I respond to that?\nAnswer : Tell her to keep her eyes half-closed all the time.",
  "Why are they all avoiding coming to the hospital?\nAnswer : They're scared of the hospital.",
  "But, Commander... don't you ever want other people to listen to what's on your mind?\nAnswer : I do.",
  "I'm not a good person. Not really.\nAnswer : That's for Pepper to decide.",
  "If I wasn't a doctor, what would I be doing instead?\nAnswer : A nurse?",
  "If you have any good ideas, feel free to share.\nAnswer : How about we place some flowers?",
  "Feeling compassion for their patients, or distancing themselves from the patients?\nAnswer : Distancing themselves from the patients.",
  "How on earth am I supposed to administer a shot to these people?\nAnswer : Distract them by talking about something else, then give them a stealthy jab.",
  "What do you think the patients would get a bigger kick out of?\nAnswer : Cosplay.",
  "By the way, are you sure you're not forgetting something?\nAnswer : A checkup?",
  "And the reasons are varied, such as because the manufacture is different, or the relationship was not good when they were human...\nAnswer : Anything I can do to help?",
  "Commander, how do you feel about white lies?\nAnswer : I think they can be a good thing.",
  "why I still work as a doctor when I'm a Nikke.\nAnswer : This is your calling. You don't owe anyone an explanation.",
  "They all ate the same food and ended up collapsing.\nAnswer : Do you have any suspects?",
  "On that note, what traits do you look for in a person, Commander?\nAnswer : Being down-to-earth."
];