module.exports = [
    "The memories you've already accumulated, or the memories you'll create in the future?\n The memories I'll create in the future.",
    "I'll let you know if you get it right?\n But if you tell me, it'll no longer be a secret.",
    "something from someone else?\n Yes, I have.",
    "What type of exercise do you think would best suit me?\n Jump rope.",
    "which do you think is more important?\n Mind.",
    "What should I take with me?\n A packed lunch.",
    "something new and something familiar, which would you pick?\n Something new.",
    "Commander, do you know why I take such pleasure in salacious activities?\n Because you like pain.",
    "I wanted to get something that you'd like.\n Something refreshing.",
    "What do you think? Get a good look at it, and make sure to feel it.\n Touch it.",
    "Do you think there's something going on?\n I'm sure she is working on some new skills.",
    "Are they a little... weird?\n I think they're very nice.",
    "Speaking of which, do you have any health tips you can share?\n Stay away from stressful situations.",
    "Doesn't that make you curious?\n Let's go right now.",
    "Doesn't it make you curious, Commander?\n I'm curious, but it kind of scares me.",
    "Is there any way I can get rid of that distance?\n Take your time and use your powers of persuasion.",
    "Commander, what do you think I would be? If I wasn't a Nikke, of course.\n ... A bounty hunter?",
    "Um... when it comes to boys, I mean.\n Tall, good-looking, and a great personality.",
    "Why do you think that is?\n Some people are just loveable. There's no reason behind it.",
    "Do I smell spicy or something?\n It's because eating spicy food is painful.",
];
