module.exports = [
  "I promise I'll go easy on you.\nAnswer : An amateur going easy on a pro?",
  "What's your milk-to-coffee ratio?\nAnswer : Milk 5, coffee 5.",
  "You know of any worthy opponents?\nAnswer : Milk.",
  "Can't I just get requests where I get to destroy things?\nAnswer : But you're a scavenger, not a destroyer.",
  "That's why I want to hire an ad agency for it. Any recommendations?\nAnswer : Mustang.",
  "She got really worked up about it. But, is it really my fault?\nAnswer : It's Frima's fault.",
  "I can't stand that annoying *vroooooom* sound.\nAnswer : Let's put a silencer on it!",
  "Do you think I look... uh... violent?\nAnswer : Not at all. I think you're cute.",
  "I wanna learn how to do that...\nAnswer : But aren't guns much better?",
  "I also need something as my mount.\nAnswer : What about me?",
  "What would you think of me wearing a dress?\nAnswer : I just might fall in love with one glance.",
  "what do you think I'd be doing?\nAnswer : Boxing.",
  "Okay?\nAnswer : Go for it.",
  "What do you think is causing this?\nAnswer : It's because of Frima.",
  "Be as objective as possible.\nAnswer : I think it's awesome.",
  "If I punched someone, how many weeks do you think they would need to recover?\nAnswer : I don't know... 12 weeks?",
  "Do you think there's something wrong with how I talk to people?\nAnswer : I get a big kick out of how you talk to me.",
  "The loser has to take a sucker punch. How about it?\nAnswer : Agreed.",
  "One's being held near here soon.\nAnswer : If you do enter, you'll be the champion for sure.",
  "Anything's good if it's got milk in it.\nAnswer : I also like milk."
];