module.exports = [
  "Now that I'm out of the office, I have no idea what to do! Any ideas?\nAnswer : Ask Poli to play with you.",
  "Should I have told her she's more like a cat instead?\nAnswer : Yes.",
  "I'm not sure how that works, though.\nAnswer : It's because rain is so inconvenient.",
  "How could they have known?\nAnswer : You can tell by the way you act.",
  "I do. I wonder if I'll ever become an accomplished police officer.\nAnswer : I'm sure you will.",
  "But, isn't working hard a good thing?\nAnswer : Yes! Nothing in the world is more important than hard work!",
  "I don't see what's so funny about it!\nAnswer : Maybe it was because you were talking too loud.",
  "What do you think I should work on first?\nAnswer : Work on your resilience.",
  "How successful do you think I'll be?\nAnswer : When they say successful, they're talking about becoming a better person.",
  "So... exactly how much do you have to eat to be healthy?\nAnswer : You have to put everything you've got into eating!",
  "I wondering what design I should draw with the ketchup.\nAnswer : A traffic sign.",
  "I'm just not sure if I can actually pull off the singing...\nAnswer : I think it'd be wonderful if you sang it.",
  "but I think it will be fun!\nAnswer : I'm sure it'll be a new experience for you.",
  "It was great seeing the looks of satisfaction on people's faces.\nAnswer : Reporting for duty even while on vacation! Very impressive!",
  "... So peaceful that sometimes there's nothing to do!\nAnswer : It's all thanks to your hard work.",
  "What do I have to do to get rid of this stigma?\nAnswer : You need to see things from a broader perspective.",
  "but what do you think is a spy's strong suit?\nAnswer : Maintaining total secrecy.",
  "Why do you think I got in trouble?\nAnswer : Because Poli cares about you.",
  "Can you help me spread the word?\nAnswer : What exactly should I tell them?",
  "I want to go with someone but I'm not sure how to ask them.\nAnswer : Play up the fact that they'll be going with you."
];