module.exports = [
    "what would you wish for?\n For you to be happy.",
    "Apparently you can only ride them in the snow.\n Would you like to ride one now?",
    "Merry Christmas!\n Merry Christmas, Anne.",
    "Do you believe in miracles?\n Yes. I believe in miracles.",
    "I don't know anything since it's my first time.\n Bring a snack or some kind of party favor.",
    "I feel so content.\n If you're happy, then I'm happy.",
    "who would it be?\n You, of course.",
    "What was the drink called again...?\n Hot chocolate?",
    "Do you often sing Christmas carols?\n When it's going to be Christmas, sure.",
    "You decide for me.\n A snowman.",
    "Neon says that if you scrunch up some snow and throw it, it makes a big explosion.\n It only did that because Neon tampered with it.",
    "Is it really true that if you hang a sock on the wall during the holidays, it'll be stuffed with gifts the next morning?\n It's true, but only for children who have been nice.",
    "I've decided. I'm going to be a mail carrier.\n Is it just because you want to ride a motorcycle?",
    "Do you think I'll have that many friends one day?\n You can achieve anything you put your mind to.",
    "Do you have a family?\n You all are my family.",
    "There's a place on the surface where the snow is piled up as high as your head!\n The next time I go to the Northern Base, do you want to come along?",
    "and Maiden does cosplay... although I'm not entirely sure what that's all about.\n It's good to have hobbies.",
    "Emma said it can be fun, but that you need to have decent drawing skills as well.\n How the cookies taste is what's important, not how they look.",
    "The line is apparently really long though.\n 	Let's go together and wait in line.",
    "and every store has a Christmas tree in their front display.\n I'm thinking of putting one in the Commander's room.",
];