module.exports = [
  "Maybe she doesn't know my name?\nAnswer : She's just a nut for firepower.",
  "So... does everything in the fridge belong to Anis?\nAnswer : Yes.",
  "Is she sick or something?\nAnswer : Maybe her head hurts.",
  "Did I... fail to protect you before?\nAnswer : This time, I'll protect you.",
  "What should I say to her?\nAnswer : Cover her in bandages.",
  "Commander, do you hurt anywhere?\nAnswer : My leg has been hurting since last night.",
  "Commander, what's your favorite place to be?\nAnswer : In the Commander's room along with you.",
  "Commander, which flavor do you prefer? Grape or apple?\nAnswer : Apple.",
  "Commander, what type person do you like?\nAnswer : The person in front of me.",
  "A blue sky, or the night sky?\nAnswer : Blue.",
  "Would you like to join us?\nAnswer : ...",
  "Commander, you should turn back.\nAnswer : ... Rapi?",
  "Commander, could I have that pen that you're using?\nAnswer : Sure, I don't need it.",
  "In the dream, you were pointing a gun at me.\nAnswer : Then what happened?",
  "Have you ever seen a mermaid?\nAnswer : No.",
  "Do you listen to any songs before you go to sleep?\nAnswer : The same song.",
  "Scissor!\nAnswer : Show scissors.",
  "I'm happy to be talking with you right now!\nAnswer : Me too.",
  "Rapi came in first, but I was second!\nAnswer : Try and finish on top next time.",
  "and then open it, it gushes out like a fountain!\nAnswer : How do you know that?"
];