module.exports = [
    "Why do you think that happens?\n People see you as a natural-born leader.",
    "What would you do whenever that happens?\n I'd listen to soothing music and meditate.",
    "Naga drops her bag, which lands on the ground with a resounding thud.\n What do you have in that bag?",
    "I know it's not much, but I prepared this for you.\n Thank you.",
    "What kind do you think would look best?\n A purple one shaped like a ribbon.",
    "Which do you prefer?\n	Cat vibes.",
    "Naga pokes me on the cheek with her finger.\n I can't believe I fell for that.",
    "What do you think the other one is?\n Not being able to wear your uniform?",
    "Could teach me how to refrain from impulse buying?\n You bought some more accessories, didn't you?",
    "That can't be an easy job.\n It can be rough. Any chance I can have a breather?",
    "Do you think all lies are bad?\n There's nothing wrong with a little white lie.",
    "Do you know any good ways to fix bad posture?\n We can try to convince her to change using desserts as a reward.",
    "She's quite charming.\n What makes you say that?",
    "On one hand, it's endearing, but on the other, it can be kind of sad.\n Mostly sad.",
    "It was so darned cute, that I just couldn't pass it up.\n Is it the one you've got on your wrist?",
    "My stomach is always in knots during this time of the school year.\n Your expression is telling me you're worried about something other than exams.",
    "At times like that, I just want to get as far away from the school as I can.\n You're more than welcome to come hang out with me anytime you want.",
    "What do you think of this new bracelet I bought?\n Did you pick it yourself? You have good taste.",
    "I hate it when they tease me for looking older.\n Maybe it's because you in fact look so young, and they're just jealous.",
    "It brings a smile to my face every time I look at her, hehe.\n Totally. She's adorable.",
];
