module.exports = [
    "who would it be?\n Ingrid.",
    "Emma's taken over the kitchen and started cooking!\n I'll try and lure her outside by telling her I'll taste her food.",
    "In your mind, what is the pinnacle of firepower?\n Such a thing does not exist.",
    "What would you be more afraid of: running out of bullets, or food?\n Bullets.",
    "Where do you think I can find the fabled blacksmith of legend, who can craft a legendary firearm for me?\n This so-called \"legendary blacksmith\" is simply the fire and brimstone in your heart.",
    "Don't you think that's unfair?\n I would say so.",
    "I don't like waiting to go up and down to and from the surface.\n You could always spend that time waiting with someone you like.",
    "Some truly ghastly food mysteriously appears. People say it's made by dead Nikkes seeking revenge on the living.\n Have you tried any of them?",
    "If I like the sound of it, I may set the same goal for myself.\n Upgrade my firepower three times over.",
    "bring back just one thing, what would it be?\n An ultra-high-tech firearm.",
    "What if that happened in real life? I wouldn't be able to shoot!!\n There is something called an emergency reload for situations like that.",
    "But... I don't want to.\n Let's eat them together. Our little secret.",
    "How can it do this to me? Doesn't it understand how this makes me feel?!\n Pull your gun on it.",
    "Why does Anis get a pass and not me? Why?!\n ... No one should be allowed to mess up the dorm.",
    "All of this rage boiling up inside me... I've got to let it out somehow!\n Let's go shoot some guns outside.",
    "Doesn't it wear her out?\n Someone has to take things seriously around here.",
    "Firepower! Firepower! Firepower!\n Firepower!",
    "or several small-caliber bullets?\n One large-caliber bullet.",
    "Let me borrow some money!\n Are you sure this isn't just an impulse buy?",
    "Why are gunpowder sparks so beautiful?\n Because that's their purpose.",
];
