module.exports = [
    "Scoops, do you know any place that will brighten up the day?\n The shelter where you're at.",
    "It's too cold today...\n Put a blanket over her.",
    "...\n Leave her be.",
    "What will you do when you feel lonely?\n I'll hold your hand.",
    "No cat toys are in sight either.\n Open an empty box and place it on the floor.",
    "Where do you think would be a good place to hide?\n How about the Commander's Room?",
    "Biscuit has been so annoying lately...\n But wouldn't it be a shame if she's not around?",
    "I wonder why.\n Maybe Biscuit is just too timid?",
    "Purr... I just feel that she smells like me.\n Because you're both cats?",
    "Scoops, what kind of weather do you like?\n Sunny weather.",
    "Meow? You smell so good.\n Could it be the milk I drank?",
    "It's time for our counseling session, but Nero hasn't shown up yet.\n Quietly swing the cat teaser in the air.",
    "I'm done washing my face.\n You wash your face just like a cat.",
    "Any idea why?\n Because Biscuit keeps asking you to play with her?",
    "Nero takes out a can of tuna.\n Shall I open it for you?",
    "Which one do you like better: cats or dogs?\n I prefer cats.",
    "Do you also want to understand cats?\n I don't mind if I don't understand them. They're cute anyway.",
    "Nero approaches me and rubs her head against my arm.\n Want some treats?",
    "...\n ... Sleepy?",
    "I feel like going somewhere high up.\n Do you want me to carry you on my back?",
];