module.exports = [
    "Are there any other animals you want to see besides polar bears?\n An arctic hare.",
    "what do you dream about?\n Of being around you.",
    "What about you, Burly Bear? Which soft drink do you prefer?\n Brown carbonated drink.",
    "I'm even sleepier than usual...\n Then get some sleep.",
    "I don't snore when I sleep, do I?\n I've never heard you snore.",
    "Is there anything in the world sweeter than sleep?\n A kiss from me.",
    "why do people get so scared when they see a polar bear up close?\n Beats me. I think they're cute.",
    "what would it be?\n There are so many. I can't possibly choose just one.",
    "what would it be?\n The Sleep Queen.",
    "I get a little lonesome.\n I can always join you.",
    "What do you think, Burly Bear?\n Polar bears are cuter.",
    "*Ya...*\n Boo!",
    "I get so sleepy.\n Ask her for some cold tea.",
    "Doesn't she remind you of a baby bunny?\n She's not as cute as you are.",
    "but I must be the only one that sleeps this much.\n Most likely.",
    "Do you like winter too?\n I do, but I like you even more.",
    "Zzzzzz...\n Don't do anything.",
    "what do you think is the softest thing in the world?\n The space in between my arms.",
    "Polar bears, grizzly bears, or brown bears?\n Polar bears.",
    "Is there any way I can keep myself from sleeping so much?\n You should sleep if you're tired.",
];