module.exports = [
  "... How exactly is it unique?\nAnswer : It looks like a firework going off mid-explosion.",
  "How strong do I look to you?\nAnswer : You've got a clear weakness, so I don't feel you're all that strong.",
  "*Sigh*...\nAnswer : You seem stressed.",
  "Besides, what reason would I have to eat with you of all people?\nAnswer : Fair point.",
  "Have you always had a such flagrant disregard for your own well-being?\nAnswer : Kinda.",
  "What are you starting at?\nAnswer : I was admiring your face.",
  "Fine, you get to ask one question. And make it quick.\nAnswer : On second thought, I'll come back when you're feeling better.",
  "What kind of thing did you think I'd do in my spare time?\nAnswer : ... Exercise?",
  "Got any ideas how I can release some tension?\nAnswer : Let's do some breathing exercises.",
  "Either of the two.\nAnswer : Maybe both of us would be here.",
  "Human, how do you like it?\nAnswer : ... Well-done?",
  "What do I need to burn?\nAnswer : I just need a small fire to cook some food.",
  "What's the secret? Does it really amount to just sticking close to you?\nAnswer : My devilish good looks.",
  "I don't think I've ever thought about it.\nAnswer : Or someone who needs protecting?",
  "From what I hear, the Ark is perfectly livable.\nAnswer : It gives us the strength to go on.",
  "Why should I tell you anything?\nAnswer : Something tells me you two aren't on good terms.",
  "Are you genuinely curious about what I do up on the surface?\nAnswer : It's not often I get to talk to someone who spends most of their time up on the surface.",
  "Who is that?\nAnswer : The commander who was at Eden.",
  "What is this?\nAnswer : Want some?",
  "How would that change anything?\nAnswer : Maybe the situation wouldn't be as dire as it is.",
];