module.exports = [
  "What can I do to change the atmosphere?\nAnswer : Change your gloomy hospital lights for brighter ones.",
  "Do you think that's true?\nAnswer : No, of course not.",
  "Commander, where do you like to take your dates?\nAnswer : The movie theatre.",
  "Why do you think that is?\nAnswer : So they could see Mary.",
  "So, what do you think I should study?\nAnswer : How to cure a patient's fake illness?",
  "So, why do people hate coming to the hospital?\nAnswer : Because getting a shot is scary.",
  "I hope they suffer more than everyone they've hurt!\nAnswer : ... I agree.",
  "What should we do?\nAnswer : Let's go on a date.",
  "Commander, please tell me your definition of a real doctor!\nAnswer : Someone who works for the patient.",
  "which one do you think can give you more energy?\nAnswer : Something refreshing.",
  "I take it that means you're feeling well?\nAnswer : Fit as a fiddle.",
  "What do you make of that?\nAnswer : I find it all very romantic.",
  "If I smile like this, do I look like her?\nAnswer : Your smile also comforts those around you.",
  "Is there any way to make it easier?\nAnswer : Give them some candy, like a lollipop.",
  "If you were in a private room, what kind of music would you like to hear?\nAnswer : Something light and hopeful.",
  "What do you look for in a significant other?\nAnswer : Someone who is bright and energetic.",
  "Commander, do you prefer movies with a happy or sad ending?\nAnswer : Happy ending.",
  "Commander... what kind of scent do you prefer?\nAnswer : You smell good even without perfume.",
  "Will there ever come a time when there are no injured or sick?\nAnswer : I'm sure that day will come eventually.",
  "When you look at me, what's the first phrase that pops into your head?\nAnswer : A doctor who makes people happy."
];