module.exports = [
  "How do I cut back on my spending and save money?\nAnswer : Keep spending. When you go bankrupt, naturally you'll stop spending.",
  "Would you splurge for good quality? Or do you always save money?\nAnswer : I'm fine with anything, so long as it tastes good.",
  "What's their problem?\nAnswer : It's because they like you.",
  "If Rapi and I got into a fight, whose side would you take?\nAnswer : Yours.",
  "I'm feeling a little upset about it.\nAnswer : Yulha isn't being fair to you.",
  "I hope nothing's wrong with her.\nAnswer : Puberty is often a very perplexing thing.",
  "But... what's your type?\nAnswer : Someone who's aloof and chic, but not TOO well put together.",
  "working for the Central Government?\nAnswer : I'm perfectly happy being a Commander.",
  "So, with that in mind, go on and try to say something that would upset me.\nAnswer : Privaty, I like you.",
  "where would you want to go?\nAnswer : The stores on Royal Road.",
  "Who else could I possibly go to the movies with?\nAnswer : Is it okay if I go with you?",
  "what kind of life do you want to live?\nAnswer : I'd like to spend my days raising a family.",
  "What are your thoughts, Commander?\nAnswer : Sounds like a fascinating plot.",
  "What kind of hairstyle do you think would suit me?\nAnswer : Nothing could top the hairstyle you have now.",
  "Your room smells nice today.\nAnswer : I just came out of the shower.",
  "If you were to make today as a special day, what would it be for?\nAnswer : Our very first time.",
  "How do you think this looks on me?\nAnswer : It's perfect.",
  "Have you had any memorable dreams lately?\nAnswer : Yes... but it'd be a bit awkward telling you about it.",
  "Did you not sleep well last night?\nAnswer : How did you know?",
  "Anything that you would kill to have right now?\nAnswer : Maybe some new clothes... or a pair of shoes..."
];