module.exports = [
    "what would you want to do?\nTake a walk while picking up bottle caps.",
    "What would you do if you were trapped in an endless maze?\nI'd ask you to come save me.",
    "Boo! Hehe, did I scare you?\nPretend to be scared.",
    "what's the first thing you'd want to do?\nI'd buy you some light croquettes.",
    "Freedom is a concept that I can't even fully comprehend.\nIf you were free, you could come see me whenever you wanted.",
    "I need to use an alias when I'm doing business.\nWhy not use your name? Quency is a fine name.",
    "What kind should I make?\nOne that leads to my heart.",
    "Got any good items on you?\nAn adult magazine.",
    "Do you prefer Guilty, or Sin?\nNone of them can beat you.",
    "Especially since I disappear pretty much on a daily basis.\nIt's not hard at all.",
    "What's the perfect woman, in your mind?\nSomeone bright and bubbly, like you.",
    "people think they can take advantage of me.\nIn the end, the person who is smiling is the real winner.",
    "What's your stance on hardened criminals?\nI don't have an opinion.",
    "What was your first impression of me?\nI thought you were pretty.",
    "Have you tried it?\nHeck no. Sounds like it'd taste like toothpaste.",
    "I just thought it would be good to know.\nI don't.",
    "Counselor! Counselor? Couuunnseellooorrrr!\nQuency! Quency? Quuiinncccyyyy!",
    "Beats me as to why. It's not like anything has been weighing on my mind.\nWe can try sleeping alongside each other.",
    "If you do, I'll call you that once I leave the rehabilitation center.\nCommander Name",
    "what will become of me?\nYou'd be right there with me, roaming freely up on the surface."
];