module.exports = [
  "what would you want to do?\nAnswer : Take a walk while picking up bottle caps.",
  "What would you do if you were trapped in an endless maze?\nAnswer : I'd ask you to come save me.",
  "Boo! Hehe, did I scare you?\nAnswer : Pretend to be scared.",
  "what's the first thing you'd want to do?\nAnswer : I'd buy you some light croquettes.",
  "Freedom is a concept that I can't even fully comprehend.\nAnswer : If you were free, you could come see me whenever you wanted.",
  "I need to use an alias when I'm doing business.\nAnswer : Why not use your name? Quency is a fine name.",
  "What kind should I make?\nAnswer : One that leads to my heart.",
  "Got any good items on you?\nAnswer : An adult magazine.",
  "Do you prefer Guilty, or Sin?\nAnswer : None of them can beat you.",
  "Especially since I disappear pretty much on a daily basis.\nAnswer : It's not hard at all.",
  "What's the perfect woman, in your mind?\nAnswer : Someone bright and bubbly, like you.",
  "people think they can take advantage of me.\nAnswer : In the end, the person who is smiling is the real winner.",
  "What's your stance on hardened criminals?\nAnswer : I don't have an opinion.",
  "What was your first impression of me?\nAnswer : I thought you were pretty.",
  "Have you tried it?\nAnswer : Heck no. Sounds like it'd taste like toothpaste.",
  "I just thought it would be good to know.\nAnswer : I don't.",
  "Counselor! Counselor? Couuunnseellooorrrr!\nAnswer : Quency! Quency? Quuiinncccyyyy!",
  "Beats me as to why. It's not like anything has been weighing on my mind.\nAnswer : We can try sleeping alongside each other.",
  "If you do, I'll call you that once I leave the rehabilitation center.\nAnswer : Commander Name",
  "what will become of me?\nAnswer : You'd be right there with me, roaming freely up on the surface."
];