module.exports = [
    "Now I won't get lost or break down any more doors.\n Congrats!",
    "Am I a bit stronger than other people?\n Yes, I think so.",
    "Are we having a joint counseling session today?\n That's just a doll.",
    "but I'm not exactly sure what to do with myself.\n Treat yourself to a nice meal.",
    "In fact, it feels like there isn't much that I need to do.\n That's because the A.C.P.U. upholds the law.",
    "Despite standing upright, Quiry keeps nodding off.\n Wake her up.",
    "People keep asking me if I'm irritated.\n I think it's because you're always frowning.",
    "Is there any other way I can better pinpoint that it's Miranda?\n Call out her name first.",
    "Do you know of any new pastimes I can get into?\n Listening to music.",
    "A calm, cool, and collected officer of the law who can handle any situation.\n You can do it, I'm sure of it!",
    "This has never happened with anyone else.\n Because I'm special.",
    "Commander! There's a bug on the desk!\n I'll catch it for you.",
    "I think we complement each other, don't you?\n No way. You'd only end up with accidents twice as big.",
    "especially since my line of work is being a police officer.\n Because you can't see certain things you'd rather not see anyway?",
    "was eating something she shouldn't have been. It was brown if you catch my drift...\n It's not what you think. It's just Splendamin in sweet potato flavor.",
    "Sorry, Commander, I didn't see the door...\n You're not hurt, are you?",
    "I can't begin to imagine what it's like. Everything is always so blurry for me.\n It's like looking at my face, but all the time.",
    "I feel bad for making Poli's life so difficult.\n Did something happen?",
    "Don't forget it next time.\n Will do. Good catch, Quiry.",
    "... Right?\n Correct!",
];