module.exports = [
    "Which of those locations means the most to you?\n The Outpost.",
    "For the sake of your own privacy, wouldn't it be better if you set up some ground rules?\n The more, the merrier.",
    "Do any memories from that time stand out to you?\n Sure, all the painful ones.",
    "How would you react?\n I'd be honest about any potential feelings I still had for them.",
    "Do you feel that way as well, Commander?\n Not at all.",
    "Commander, If we ever reclaim the surface, what's the first thing you would do?\n I'd go on a nice spring picnic outdoors.",
    "How can I prevent this from happening?\n Your already short skirt will end up becoming even shorter.",
    "to live in the old days?\n People probably led much safer lives back then.",
    "...\n Is it when they're teasing you?",
    "On the plus side, it's increased the number of troops we have available, but it's also led to a few more altercations and other incidents.\n We can go on patrol together.",
    "What do you think I should do?\n Complain while you eat.",
    "What does it mean?\n It's about your troubles melting away.",
    "I wonder... will I ever find something that means that much to me?\n We can take our time finding it. Together.",
    "Could there be something else going on?\n Yep, there's definitely a ghost in the showers.",
    "I don't understand why Anis acts this way.\n There's a legend that if you open and close it 100 times, pudding will come out.",
    "She never cleans up, not even a little bit.\n I'll talk to her.",
    "Surely there must be a way to get things done more efficiently...\n I can help you.",
    "As such, I've been thinking of picking up a hobby.\n Just kick your feet up and while the hours away.",
    "What are your opinions on private personal space?\n It can get lonely sometimes.",
    "Food supplies in the Outpost are dwindling.\n I'll only eat half-portions from now on.",
];
