module.exports = [
  "Oh! Oh my...!\nAnswer : We should go outside and get some fresh air.",
  "What should I do?\nAnswer : Grieve as much as you want, then move on when you're ready.",
  "Do you know why that could be?\nAnswer : Maybe you're too aware of your own immorality.",
  "What kind of books do you like?\nAnswer : Erotic and romantic novels.",
  "What is your fetis... I mean, what is your ideal type?\nAnswer : A person who is true to their own desires.",
  "Do you just ask politely? Or do you really go for what you want?\nAnswer : I just ask politely.",
  "How is life in the Ark?\nAnswer : It's unbearable.",
  "Curious, I opened the shower door just a crack and peeked inside...\nAnswer : Stop! It's the A.C.P.U.!",
  "Do you think we Nikkes have souls as well?\nAnswer : I think Nikkes must have them.",
  "Believer, do lead with the lips or the tongue?\nAnswer : ... What?",
  "Gasp!\nAnswer : What? What do you see?",
  "... Can you pray with me for all of the sisters that we lost?\nAnswer : Pray without saying a word.",
  "It's worlds apart from the rest of the surface.\nAnswer : One day the surface will be like this. I'll make it so.",
  "How about we do the same?\nAnswer : Honey.",
  "Chef\nAnswer : Fond.",
  "I don't want to forget a single second of it.\nAnswer : Let's keep creating new memories.",
  "I found this beautiful area where you can see flowers as far as the eye can see.\nAnswer : I'd love to see it for myself.",
  "Do you visit the library frequently?\nAnswer : I've read most of their entire book collection at this point.",
  "Believer, do you own anything that has sentimental value, but no practical usage?\nAnswer : Sure I do.",
  "Are you any good at whistling?\nAnswer : Yes."
];