module.exports = [
    "I got something for you.\n Accept her gift.",
    "And it's the subject I'm worst at.\n I bet you still did pretty well, right?",
    "How about you, Teacher?\n I find them a bit scary too.",
    "This is 1, this is 2, and this is 3.\n Naru 3...?",
    "Hehe. You know why?\n Because they're your personal snack and homework assistants?",
    "*Sigh* I wasn't like that when I was their age.\n Juniors these days need to be put in their place.",
    "You know, someone who can command respect and admiration for a long time.\n Someone who treats others to meals and snacks",
    "That's completely unacceptable!\n Did Ein ask you to clean the window frames?",
    "I mean, it's a great idea, don't you think?\n Yeah, that would be awesome.",
    "Wanna try some?\n Sure thing, hand 'em over.",
    "Teacher, my teeth are throbbing.\n Let's get you to a dentist.",
    "Too much fish and now my tummy aches♪ Ooh la la♪\n Emperor penguins hate spinach♪ Ooh la la♪",
    "Plus, we can jam to some tunes!\n What kind of snacks should we get?",
    "So, what do you think? Am I reliable?\n Absolutely reliable.",
    "...\n Give her a piece of sweet chocolate.",
    "Teacher, did you do well on tests back in your days?\n I was the valedictorian.",
    "What's the secret to being a great one?\n You already are a great senior, Rei.",
    "Do you have any tips?\n Drink milk every day and you might grow taller.",
    "Teacher... Naru... Naru...!\n Did Naru steal your snacks?",
    "when I'm not feeling up to going to school?\n It's okay to skip class once in a while, but don't make it a habit.",
];