module.exports = [
    "What do you think would look good on me?\n Subtle, neutral colors.",
    "Can I rest a little?\n Of course.",
    "Rosanna taps her lips twice with her fingers.\n Tap your own lips twice.",
    "Any last words?\n I-I'm sorry I never got to see the surface!",
    "If you had to choose between the head or heart, which would it be?\n Head.",
    "Where do you plan on taking me?.\n The hotel.",
    "What scares you more: a knife or a gun?\n Knife.",
    "What do you think?\n They probably fear you.",
    "...!\n *Bang bang!*",
    "At times like this, it's best to...\n Try talking.",
    "Any ideas on how I can handle her?\n I'll talk to her.",
    "So handsome.\n I'd appreciate it if you stopped staring.",
    "If you were in this situation, Mister, what would you be thinking?\n That he'd betrayed me.",
    "Is there anything fun to do around here?\n We could play a board game.",
    "Got any booze around here?\n How about we go out for a drink after our session?",
    "... Duck!\n Duck at once.",
    "what would you do?\n I'd call the A.C.P.U.",
    "How about decorating it a little more?\n Think I should get a fancier carpet?",
    "They know that if they're caught, they'll pay with their lives, but they keep popping up.\n Sounds exhausting.",
    "Where'd you get the confidence to be like this?\n From you.",
];