module.exports = [
    "but you already had one at home, what would you do?\nIt doesn't matter. I buy everything I want.",
    "I make billions every month... But when I actually look at my bank account, it's always empty...\nThat is such a scary story.",
    "Do you have some time this weekend?\nOf course.",
    "Hey, Sweetie. Notice anything different about me today?\nAre those new heels?",
    "Is there any way to make money without working?\nInvest in real estate or stocks...",
    "They say I should be investing my earnings, not spending it all...\nMoney exists to be spent!",
    "What should I put on the main banner this week?\nA product with unrealized potential.",
    "Do you know what it is?\nThat I don't spend mindlessly?",
    "What type of pattern do you think is the most beautiful in the world?\nLeopard print.",
    "But, I figure someone like you would have a very different bucket list than I do.\nEnsuring the safety of innocent people.",
    "...\nTrying to get your hands on a limited edition item?",
    "I don't think I've ever seen you spend a single credit.\nI do a bit of spending here and there whenever I need something.",
    "Isn't that crazy?!\nYou're kidding! I'm totally obsessed with Ashe.",
    "They'll feel bad if I stand them up... Which one should I attend?\nYou should hold your own event.",
    "I need to invite a guest that'll create some attention. Who do you think would be good?\nInvite Mustang.",
    "Sweetie, how do you feel when you watch rich people go on a spending spree?\nI find it therapeutic.",
    "Sweetie!\nI'm sure you'll get the next limited edition... whatever it was.",
    "Do you remember the name of my clothing brand?\nRusae.",
    "Why would someone do such a thing?\nThey just hate us, 'cause they aint us.",
    "Catch ya on the flip side!\nWhat on earth is going on?"
];