module.exports = [
  "Which type of tea do you like?\nAnswer : Black tea.",
  "and you couldn't tell if the decision you were making was the right one?\nAnswer : I would believe in myself and keep moving forward.",
  "Are you this way with everyone?\nAnswer : No, only with you.",
  "How do you feel when you see them?\nAnswer : I feel very excited.",
  "What about you?\nAnswer : I've been exercising.",
  "What would you do if you were me, CommanderName-kun?\nAnswer : Just give it up.",
  "I'll prepare some in the courtyard for you for the next time you visit.\nAnswer : Cherry blossoms.",
  "what's your general approach?\nAnswer : Stick to the procedure.",
  "What do you look for in a partner?\nAnswer : Someone with grace and sangfroid.",
  "When she read my fortune, she mentioned your name. What do you think that means?\nAnswer : It certainly sounds positive to me.",
  "What should I do?\nAnswer : How about I come visit and keep you company?",
  "It's hardly appropriate for someone in your position to look that way.\nAnswer : I know. I'm so helpless. Help meeeee, pretty please with a cherry on top?",
  "how would you express yourself to her?\nAnswer : I think I'd talk to her face to face.",
  "Do you have any recommendations?\nAnswer : The Mistress and Her Dog.",
  "but I don't feel terribly comfortable while I'm doing it.\nAnswer : The consequences of one's actions, both good and bad, should always be clear.",
  "What goes through your mind when you see the first cherry blossoms of the year?\nAnswer : I think about Sakura.",
  "Do you have any memorable childhood memories, CommanderName-kun?\nAnswer : The hospital.",
  "How can I access that gentler side of myself?\nAnswer : It's also important to be comfortable with who you are.",
  "They've got lots of materials their customers can use to create their own confections.\nAnswer : Why don't we go and buy some sometime?",
  "Have you ever fired a matchlock rifle, CommanderName-kun?\nAnswer : I haven't, but I'd love to."
];