module.exports = [
  "What about you, Commander? What do you think of her?\nAnswer : I think she's a good person as well, and very friendly.",
  "Would... would I get in trouble if I did?\nAnswer : You won't be in trouble.",
  "C-commander, if you were in a relationship, what kind of relationship would you like to be in?\nAnswer : I'd want it to be a relationship full of passion, like the ones on TV.",
  "would you rather stay home or go out?\nAnswer : I'd have a staycation at home and binge watch all my favorite shows.",
  "Honestly!\nAnswer : Someone I can watch my favorite shows with.",
  "Are you in any pain?\nAnswer : Is the protagonist on your TV show terminally ill?",
  "Do you think something happened to me last night?\nAnswer : You probably danced in your sleep.",
  "Can I dress in office attire, starting tomorrow?\nAnswer : Are you sure Delta will be okay with this?",
  "What do you think about rain, Commander?\nAnswer : I enjoy the rain. I find it very atmospheric.",
  "Do you think that's true, Commander?\nAnswer : I think it's true.",
  "would you say hi?\nAnswer : I'd just stare from a distance as they passed by.",
  "What do you think?\nAnswer : It's adorable.",
  "This new show I've been looking forward to premieres tonight.\nAnswer : What's the show about?",
  "If it were you, Commander, how would you handle it?\nAnswer : I would try to hint at what my issues are.",
  "Commander, what kind of music do you usually listen to?\nAnswer : The Waiting on Love OST, the first track.",
  "... Never mind, it's nothing.\nAnswer : That show you've been watching is starting soon. You can leave early today.",
  "It would be nice if I could meet that person who was in my dreams someday...\nAnswer : I'm sure one day your dream will become a reality.",
  "What should I do if I feel resentment towards one of my squadmates?\nAnswer : You should let them know. Don't keep it bottled up inside.",
  "I'd love to visit one for real someday.\nAnswer : Actually, you could say I'm in a flower garden right now.",
  "what's your opinion on white lies?\nAnswer : I think it's needed in some situations."
];