module.exports = [
  "What would you do?\nAnswer : Rock, paper, scissors.",
  "I'm considering whether to say something to her about it.\nAnswer : I'm sure her nonchalant attitude must have helped you out in the past.",
  "Choose only one thing.\nAnswer : There is unlimited food.",
  "Does it make you feel full? Is it easy to preserve?\nAnswer : I'll get you some.",
  "How do humans keep their minds sharp?\nAnswer : Showers.",
  "Do you agree?\nAnswer : If communication is possible, I will try talking to them first.",
  "I don't know how I should react when that happens.\nAnswer : It's best to ignore her.",
  "Is that true?\nAnswer : It's sad, but it's true.",
  "There is more than enough to live on here. Why do you still dream of reclaiming the surface?\nAnswer : Because this place won't be safe forever.",
  "I am curious. What is your secret?\nAnswer : I'm not sure.",
  "Snow White is checking her gears.\nAnswer : Wait a little longer.",
  "Do you think we'll ever reclaim the surface?\nAnswer : I do, because I have faith in you.",
  "Humans are just tools to them.\nAnswer : I'll keep that in mind.",
  "Does the surface frighten you?\nAnswer : A little bit.",
  "How would you respond to this question?\nAnswer : I wouldn't go back.",
  "If it was you, what road would you choose?\nAnswer : The new road.",
  "is there anything else you always take up to the surface?\nAnswer : Small snack-sized bits of Splendamin.",
  "But I don't want to drink. When I'm drunk I tend to be less aware of my surroundings.\nAnswer : Since she's lonely, you should keep her company. You can drink water.",
  "have you ever given the future much thought?\nAnswer : We'll make a new Outpost on the surface that we can live in.",
  "which would you prefer?\nAnswer : They all sound terrible."
];