module.exports = [
    "What would you do?\nRock, paper, scissors.",
    "I'm considering whether to say something to her about it.\nI'm sure her nonchalant attitude must have helped you out in the past.",
    "Choose only one thing.\nThere is unlimited food.",
    "Does it make you feel full? Is it easy to preserve?\nI'll get you some.",
    "How do humans keep their minds sharp?\nShowers.",
    "Do you agree?\nIf communication is possible, I will try talking to them first.",
    "I don't know how I should react when that happens.\nIt's best to ignore her.",
    "Is that true?\nIt's sad, but it's true.",
    "There is more than enough to live on here. Why do you still dream of reclaiming the surface?\nBecause this place won't be safe forever.",
    "I am curious. What is your secret?\nI'm not sure.",
    "Snow White is checking her gears.\nWait a little longer.",
    "Do you think we'll ever reclaim the surface?\nI do, because I have faith in you.",
    "Humans are just tools to them.\nI'll keep that in mind.",
    "Does the surface frighten you?\nA little bit.",
    "How would you respond to this question?\nI wouldn't go back.",
    "If it was you, what road would you choose?\nThe new road.",
    "is there anything else you always take up to the surface?\nSmall snack-sized bits of Splendamin.",
    "But I don't want to drink. When I'm drunk I tend to be less aware of my surroundings.\nSince she's lonely, you should keep her company. You can drink water.",
    "have you ever given the future much thought?\nWe'll make a new Outpost on the surface that we can live in.",
    "which would you prefer?\nThey all sound terrible."
];