module.exports = [
  "mugwort-flavored or garlic-flavored Splendamin, then you'll become an adult. Is that true?\nAnswer : It's true.",
  "But... have you been there before?\nAnswer : I haven't.",
  "Do you think she is too mean to me?\nAnswer : Yes.",
  "What should I do?\nAnswer : Buy Diesel a new flavor of candy.",
  "Which one would you date?\nAnswer : The mature one.",
  "What do I have to do for them to stop seeing me as cute?\nAnswer : Chug a cup of bitter coffee in front of them.",
  "I'm so angry. How should I take revenge on them?\nAnswer : Next time you see them, report them as missing children as well.",
  "Argh. I'm so angry! It's so annoying!\nAnswer : That person just hasn't seen your competence yet.",
  "N-never mind.\nAnswer : Do you want some candy?",
  "Then I'll grow taller and look more like an adult!\nAnswer : Good luck.",
  "Preferably something sweet.\nAnswer : You're just going through a growth spurt.",
  "Traveling on a train... something like that.\nAnswer : Sure we can. Let's start planning our itinerary.",
  "How rude!\nAnswer : We'll go to a different café next time.",
  "Or do you prefer someone smaller... like me?\nAnswer : Personally, I prefer shorter women.",
  "First up is how I dress. What kind of clothing should I wear?\nAnswer : Something that's all business.",
  "A... honeymoon, was it? Have you heard about this before?\nAnswer : It'd be nice for you and I to go on a honeymoon.",
  "Do you think they feel the same way about me?\nAnswer : I'm sure they do.",
  "Strawberry candy is one thing, but strawberry toothpaste? No thanks.\nAnswer : It probably tastes nice and sweet.",
  "So it made me curious.\nAnswer : Of course, she's standing right in front of me.",
  "I'd like to see Brid and Diesel try and do this on their own. Then they'd see how hard it is.\nAnswer : I'll help you with the cleaning."
];