module.exports = [
    "Ahahaha! You should see the look on your face, Commander!\n I can't see! Help!!",
    "Do you know what it is?\n A pearl?",
    "What do you think, Commander?\n I personally prefer your swimsuit, Anis.",
    "I made this sand castle all by myself. What do you think?\n ... Castle? Where?",
    "Come and get me, Commander!\n I'm gonna get you!",
    "Can you apply some sunscreen on my back?\n Sure. Turn over.",
    "What's the tastiest thing you've sampled up here so far?\n Barbecue.",
    "Well, I have a bloodcurdling story to share with you, Commander.\n Anis! Be-Behind you!",
    "What if I find out I don't like soda as much when we return to the Outpost?\n You can just come back to the seaside again.",
    "what do you think of my swimsuit?\n You should take good care of it so you can keep wearing it in the future.",
    "I wanna test you: do you know what kind of bird it was?\n A seagull.",
    "Under the red hot sun♬\n You and me, just two of us♬",
    "I wonder if I was a fish in my previous life?\n You may be onto something.",
    "but I couldn't sleep.\n Want to hang out for a while?",
    "Isn't the color of this shell lovely?\n It's the same color as your hair.",
    "Waddya say we both take shelter under this beach umbrella?\n Much appreciated.",
    "I wonder what new variations will appear in the future?\n What about windpower?",
    "How can I live without my precious carbonated beverages?\n How about I give you some of mine?",
    "Don't you think sunset is prettier than sunrise?\n How about we crack open a soda and take in the sunset?",
    "I'm so jealous that you can swim.\n I actually prefer staying out of the water.",
];