module.exports = [
    "I was thinking of tying my hair back to switch up my image. Hehe.\n You're perfect just the way you are.",
    "It's so pathetic.\n Like that crocodile?",
    "I get so sad.\n Is it because you're worried about your future?",
    "Do you prefer soft or hard objects?\n Hard.",
    "this incredible feeling wells up inside me, and I can't control it.\n I think I might know that feeling you're describing.",
    "You should have seen the owner. They were stunned.\n That's all you ate?",
    "Some even ask for my personal information.\n That's because you take such stunning photos of desserts.",
    "what would I wish for?\n Free desserts for life.",
    "Tia runs into my arms and gives me a big hug.\n You shouldn't act like this when we're in public.",
    "What do you think she was doing there?\n Maybe she heard some students were hanging out there late at night, and she wanted to check up on them.",
    "Wouldn't you agree?\n I agree.",
    "Maybe I've been studying too hard?\n You've got to maintain good posture during class.",
    "Isn't it adorable?\n Which one? The chameleon?",
    "What about you, Teacher?\n I just drink coffee.",
    "What animal do you think is in the pattern?\n A dragon.",
    "What do you think I'm doing wrong?\n I think it's a problem with the focus.",
    "Are you busy right now?\n No.",
    "I think that's why I depend on her so much.\n I think I know what you mean.",
    "What do you think, Teacher?\n It's all about quality, not quantity. The taste is what's important.",
    "when you were little, what did you want to be?\n A teacher, of course.",
];