module.exports = [
    "or clean the bathroom?\n Neither.",
    "Master, what do you think makes bunny outfits so mesmerizing?\n Their adorability.",
    "As I wake up, I can faintly make out a blurry white furball moving in front of me.\n Gently pet it.",
    "Woohoo! What kind of genre do you like?\n Rom-coms.",
    "Do you know any ways to remove bad luck?\n I'm not too sure... I only believe in myself.",
    "who would you want to see?\n I can't decide...",
    "Odd or even?\n Even.",
    "What should I wear?\n A maid outfit.",
    "So, what scent do you think would best suit me?\n Sweet baby powder.",
    "What do you think they meant?\n Maybe they think you're as cute as a rabbit.",
    "Guess what it was about!\n Cleaning.",
    "What are you in the mood for, Master?\n Some dessert.",
    "What should I serve to make her happy?\n Omurice.",
    "Is there something you wanted to say?\n You look adorable in that rabbit outfit.",
    "What do you think they are doing right now?\n They're probably missing you loads too.",
    "Tell me, what should you do first when cleaning the floor?\n Sweep the floor.",
    "I wonder where I can learn to make a bed so neatly?\n I think you're capable of doing it now.",
    "If you suddenly had a lot of money, what would you spend it on?\n I'd go to the Maid Cafe every day.",
    "What's your favorite color, Master?\n Green.",
    "you just can't help but fall in love with it?\n Twinkling Rabbit.",
];