module.exports = [
    "who do you suppose comes closest to being the perfect maid?\n You.",
    "Agh!\n Grab Privaty.",
    "Would you like to listen?\n I'd prefer to hear your voice.",
    "M-Master?! Y-you didn't see that just now, did you?\n Make a heart gesture with your hands to Privaty.",
    "I just don't get it.\n Privaty, Privaty, on the count of three, you will fall in love with me! 1... 2...",
    "Why do you keep staring at me?\n Because you're so pretty.",
    "but I don't know what to draw...\n How about your face?",
    "Is there anything special you'd like me to prepare for you?\n I'm sure I'll like anything you make.",
    "What's your favorite dessert, Master?\n I like pretty much anything that's sweet.",
    "Why do you think they were doing that?\n Because you're so adorable in that outfit.",
    "I have to say, it feels good whenever that happens.\n *Pats Privaty on the head*",
    "are you back?\n I'm back, my little kitty cat.",
    "It's not like anything I've had before, but it wasn't half bad.\n I'm a big fan of ketchup cake as well.",
    "What do you think about being called Master?\n It feels wonderful when you call me that.",
    "I absolutely hate cleaning.\n You're free to hide in the Commander's Room.",
    "I can't wait to take it off.\n You can always change into something more comfortable here.",
    "would you rather have me or Drake?\n You.",
    "how many stars would you give my service?\n Five stars, obviously.",
    "what do you think of my outfit?\n It looks good on you.",
];