module.exports = [
  "What do I need to do... to not be n-nervous in front of people?\nAnswer : Be aware of your own cuteness.",
  "How should I decline?\nAnswer : Make Emma taste her own food.",
  "H-how can I make it stop?\nAnswer : Close your eyes for 3 seconds, then open them again.",
  "Do you have an i-ideal type?\nAnswer : Someone small and cute.",
  "But, I'm worried, because my writing is so ugly...\nAnswer : It might be prettier than you think. Let me see it.",
  "H-how can I fix this?\nAnswer : There is no need to fix it. It's a natural thing.",
  "Do you have your own way of relieving stress?	\nAnswer : I go out and be social.",
  "Vesti looks upset.\nAnswer : I am sorry I haven't been able to spend time with you these days.",
  "... If you had someone you hate so much that you wanted to destroy them, what would you do?\nAnswer : Ignore it and think about something else.",
  "I want to have a counseling session with you every day.\nAnswer : I enjoy having counseling time with you, too.",
  "is there anything you only do with people that you're close to?\nAnswer : Being at ease while I talk with them, like right now.",
  "What's your favorite movie genre?\nAnswer : Animated movies with cute characters.",
  "have you ever had a crush on someone?\nAnswer : No, I haven't.",
  "What do you do when you are overwhelmed with loneliness?\nAnswer : I write in my journal to try and give words to my feelings.",
  "what are you thinking about?\nAnswer : Not much.",
  "Do you make any resolutions for the new year?	\nAnswer : To forge a greater bond with you.",
  "What do you think about people decorating their diaries?\nAnswer : I think it's cute.",
  "Is there a way to keep your feelings from being hurt?\nAnswer : I wouldn't let it get me down and just move on.",
  "There this person... and I want them all for myself.\nAnswer : The more you obsess about someone, the more you'll just drive them away.",
  "who do you like the most? Who are you most comfortable being around?\nAnswer : You're my favorite, and I'm most comfortable around you."
];