module.exports = [
  "If you had to choose between simple and fancy, what would it be?\nAnswer : Simple.",
  "No questions.\nAnswer : B.",
  "do you eat the cherry right away, or save it for last?\nAnswer : I usually eat it first.",
  "Do you prefer the Ark, or the surface?\nAnswer : The Ark.",
  "Her toes move up towards the inside of my calf.\nAnswer : Grab Viper by the ankle.",
  "Do you prefer crows or snakes?\nAnswer : Snakes.",
  "should I tell you about a secret I've been hiding?\nAnswer : If you tell me, what will you want in return?",
  "I want to go somewhere.\nAnswer : Want to go on a date?",
  "Do you think that's why Crow likes Jackal more than me?\nAnswer : You have plenty of your own positive qualities.",
  "What's the best thing about living in the Outer Rim?\nAnswer : I get to see you often.",
  "What do you think I should do with them?\nAnswer : Just don't kill them.",
  "do you like eating it in one bite, or letting it melt slowly in your mouth?\nAnswer : Letting it melt slowly in my mouth.",
  "Someone who steals, or someone who gets stolen from?\nAnswer : Being stolen from.",
  "what do you think would be the first thing I'd do?\nAnswer : ... Kill me?",
  "Wanna guess why?\nAnswer : Because today is our scheduled counseling day?",
  "are always reciprocated?\nAnswer : What do you think?",
  "I've got something to do.\nAnswer : Okay.",
  "how innocent you are?\nAnswer : ... Is that a compliment?",
  "Honey, do you like alcohol?\nAnswer : I do.",
  "My makeup didn't come out right, and my hair is a mess.\nAnswer : I didn't expect you to care about stuff like that."
];