module.exports = [
  "What do I need to do to sell products to people like you?\nAnswer : Use your beauty.",
  "You should remind Dolla of that.\nAnswer : Understood.",
  "Is there anything you want to eat right now?\nAnswer : Anything is okay, if it's from you.",
  "What should I do with her?\nAnswer : Demand an appropriate share of the profit.",
  "Do you want to be my secretary?\nAnswer : What are the conditions?",
  "Did you bring back anything, by any chance?\nAnswer : Some Rapture parts.",
  "Like an umbrella, or a raincoat.\nAnswer : What's your asking price?",
  "What do you think of Nikkes who talk with an accent?\nAnswer : Sounds cute.",
  "What is it? Tell me.\nAnswer : Red.",
  "What do you think I'll be doing in 10 years?\nAnswer : You'll be expanding your business on the surface.",
  "what is the most important factor in success?\nAnswer : Luck.",
  "Do you have a lot of dating experience?\nAnswer : I've been single my entire life.",
  "I want to make a note of it for when I release my next product.\nAnswer : You've caught my eye.",
  "We just released a new flavor of soda, want to try it?\nAnswer : I'm willing to try anything you offer me.",
  "Some of them really cross the line.\nAnswer : I'll take care of them for you.",
  "When you look at me, what words pop in your head?\nAnswer : A businesswoman who doesn't take crap from anyone.",
  "or do you prefer having a sense of stability?\nAnswer : I enjoy challenging myself",
  "Is there anything you've seen recently that you want to get your hands on?\nAnswer : Yan's heart.",
  "What's your definition of failure?\nAnswer : Failure is just another opportunity to try again.",
  "I'm on the hunt for investment opportunities.\nAnswer : You're the only thing I want to invest in."
];