module.exports = [
  "Ugh... Why are you staring at me?\nAnswer : Do you have a bad hangover?",
  "*Sigh* What should I do?\nAnswer : Still, shouldn't you say what's on your mind?",
  "But I don't think it's good for a kid to be so mature, anyway.\nAnswer : Give her a vacation and send her to the Outpost.",
  "So, what should I eat? Something sweet, or something spicy?\nAnswer : Sweet.",
  "*Sigh*\nAnswer : I'm sorry, but that is impossible.",
  "Do you have somewhere you want to go on your vacation?\nAnswer : I'll just rest in the Commander's room.",
  "Instead of being a Commander, I mean.\nAnswer : I did.",
  "How can I get rid of her?\nAnswer : Bite her.",
  "Triangle will execute you?\nAnswer : I know.",
  "Do any of the Nikkes suit you?\nAnswer : Someone like you.",
  "Do you think there's any truth to that?\nAnswer : I think it's complete nonsense.",
  "What should I do in a situation like this?\nAnswer : I'll sing you a lullaby.",
  "Do... do you think ghosts really exist?\nAnswer : Of course they don't.",
  "Hmm...\nAnswer : Don't do anything.",
  "what kind of weather do you prefer?\nAnswer : A sunny day.",
  "is there anything you hope comes true this year?\nAnswer : That you take it easy for a while.",
  "What do you usually think about when you're in the shower?\nAnswer : I don't think about anything.",
  "I want to drink something new. Is there anything you can recommend?\nAnswer : An energy drink.",
  "what would you ask?\nAnswer : When do you find time to rest?",
  "Newbie, why am I so tired?\nAnswer : Because you've been working all day. "
];