module.exports = [
  "Is she sick of me or something?\nAnswer : Use physical force to keep her with you.",
  "but I don't have enough money to get both!\nAnswer : Tie Mihara up with the whip.",
  "Commander, do you know what happens to a Rapture once it's captured?\nAnswer : ... They probably get disposed of.",
  "Why? I'm much better with a whip than a gun.\nAnswer : Because Raptures don't feel any pain.",
  "Is there anything I can do to change my sleeping habits?\nAnswer : Find something to hold onto before you go to sleep.",
  "what should I do? I certainly won't be able to capture Raptures anymore.\nAnswer : Just live out your days in peace.",
  "But what's the point of tying a knot if you don't make it tight?\nAnswer : You should tie Mihara up, too.",
  "How would you feel if someone suddenly hit you, out of the blue?\nAnswer : One-sided violence is never good.",
  "Should I buy a new pair?\nAnswer : Is it really that big a deal that the handcuffs are broken?",
  "A hit to the shins? A punch to the gut? Stubbing your toe?\nAnswer : I haven't been hit that much, so I really can't say.",
  "What would you say is my strong suit?\nAnswer : You're pure of heart, and kind.",
  "What does it taste like?\nAnswer : When you're a little older, we can go try a few together.",
  "means the world to me.\nAnswer : I'm sure Mihara likes you as well.",
  "I'd prefer to be alone today.\nAnswer : Caress her hair.",
  "I'm not bothering you by talking to you every day, am I?\nAnswer : You've never bothered me, not even once.",
  "I want to show you something fun.\nAnswer : You reach out your hand.",
  "Do I really have to go?\nAnswer : It's important to read up on things you're learning as well.",
  "Do you like me?\nAnswer : Yes, I do.",
  "I'm so exhausted...\nAnswer : Do you want to sleep here?",
  "Commander, when are you most happy?\nAnswer : When I'm spending time with you."
];