module.exports = [
    "but I don't know how to express that and tell them how I feel.\n I don't think you have to tell them. I'm sure they already know.",
    "Are seahorses good or bad at swimming?\n They're bad at it.",
    "What should I do?\n Wait for her to open up.",
    "how long can you stay underwater?\n 32 seconds on the dot.",
    "I'm so sleepy.\n You can take a nap on my bed if you want.",
    "I think I've got nearly every line memorized by now.\n I'll keep the pirate-related movies somewhere out of reach.",
    "I get kinda jealous whenever I see Morgan talking to Mast.\n You're connected to them on a spiritual level. They don't have to speak.",
    "Why doesn't the Ark have one?\n We should hurry and reclaim the surface.",
    "Do you think that kind of outfit would suit me?\n I am a tad curious how you'd look in uniform.",
    "What do you think I can do to make it not as lonely?\n Raise marine life on it.",
    "What should I prepare?\n Nutrium would be a good choice for a party.",
    "Got any good suggestions?\n Let's put our brains together and think.",
    "Helm will probably give me an earful if I ask the marine life to take over for me.\n I can help you.",
    "is there anyone else here aside from us?\n No, why?",
    "Starfish are getting a bit stale for me.\n Octopus?",
    "What kind of swimsuit should I choose?\n Something cute with frills.",
    "If I hadn't become a Nikke, what would I be doing?\n You'd be a member of the navy rescue team.",
    "What should I do when my head hurts?\n Touch Anchor's forehead.",
    "Marine life have faces only a mother could love, don't you think?\n That's part of their charm.",
    "Are you good at fishing, Captain?\n I'm a master angler.",
];
