module.exports = [
    "which seats do you prefer?\nThe ones closest to the stage.",
    "If you had some time off, what would you do?\nTravel far away to somewhere exotic.",
    "which one will you pick?\nI don't need either of them.",
    "Did something happen there?\nIt's home to a poor soul who has forgotten how to sing.",
    "or the ending of a song is more important?\nThe beginning.",
    "if we ever reclaim the surface, what's the first thing you'll do?\nFind higher ground and shout to the heavens that we have retaken the surface.",
    "Maestro, are you a fan of hard-hitting music?\nI am. It helps me identify with Volume.",
    "If she was feeling down when you saw her, what would you do?\nI wouldn't do anything. It's the path she chose.",
    "I want to do something exciting. Something spontaneous.\nTry to practice singing outdoors.",
    "The unfolding stories, the expectation of the audience, and the arrangement made with everyone. All of this is up on me.\nYou'll always have your music, Aria.",
    "What do you think its secret is?\nOpera is eternal.",
    "If it were you, what would you do?\nI'd try to convince him that I was right.",
    "What can I do to improve?\nJust focus on the music.",
    "What should I do to help him?\nLet him handle it on his own.",
    "comedies or tragedies?\nTragedy.",
    "Have you ever considered what the perfect death would be?\nSacrificing yourself for a noble cause.",
    "Are any of them your type?\nYou are, Aria.",
    "What are some recreational activities I could have fun with?\nGo sing some karaoke.",
    "Maestro, have you ever hit a snag before?\nOf course, it's common.",
    "In the end, who would you compose for?\nFor myself"
];