module.exports = [
    "Shall we start the concert?	\n You mean counseling?	",
    "I will make sure that all the wishes of my people are fulfilled.	\n Is that your wish? Incredible.	",
    "What is your reason for doing so?	\n Perhaps it's the same reason that you take care of your subjects.	",
    "you, Chime, and I must return to the Crown Kingdom.	\n It's a pity I can't join you.	",
    "when she's with you?	\n Kind and warm-hearted.	",
    "Is there anything you would like to know about the Crown Kingdom?	\n How did you become the king?	",
    "a king's purpose is?	\n To lead the country as the citizens see fit.	",
    "and so the responsibility weighs ever heavier on my head.	\n That seems difficult to handle alone.	",
    "Do you have no intention of coming to the kingdom with us?	\n I'm sorry, but I don't.	",
    "What kind of food is popular in the Ark?	\n You're always spoiled for dessert choices in the Ark.	",
    "What kind of weather do you prefer?	\n Clear and sunny weather.	",
    "I always feel so safe and secure when Chime is at my side.	\n I'm sure she feels the same way about you.	",
    "...\n Don't say anything and wait.	",
    "What does it taste like?	\n Would you like to try some?	",
    "I can feel Crown staring me down, which is unnerving.	\n Is this interesting to you?	",
    "I haven't seen her for a while.	\n Maybe she went out to scout the surroundings.	",
    "of leading a kingdom?	\n Comporting yourself like a true king.	",
    "just like Chime and I.	\n I think the Counters and I might have a stronger connection.	",
    "Ugh...	\n Are you feeling unwell?	",
    "I would be quite interested in seeing what such a kingdom looks like.	\n If you're curious, you can come visit anytime.	",
];
