module.exports = [
    "Are you bored or something?\n Yes.",
    "What should I do?\n Give her some better strawberry candy.",
    "What can I do to cheer her up?\n Ask Soline to stay away from Brid for a while.",
    "Commander, do you like soft flavors or strong flavors?\n Strong.",
    "AZX is coming through! Ding dong!\n She's out of tune, but just let her sing.",
    "Commander, did you like Ark Rangers when you were a kid?\n I was a huge fan.",
    "What should I do?\n The AZX is already perfect. No need to decorate.",
    "what would you do, Commander?\n Practice my singing.",
    "What would I be doing if I hadn't come to work at Arc Express?\n Probably a pop idol.",
    "would you want to go back and change anything?\n Yes.",
    "where would you go?\n Somewhere near the ocean where I could hear the sound of crashing waves.",
    "What's your favorite color, Commander?\n Blue.",
    "What type of clothing style do you like?\n Cool and casual.",
    "Is there anything else I could get her to drink instead of coffee?\n Make her a sweet strawberry latte.",
    "What's your favorite smell?\n Sweet fruits,",
    "In your mind, what's the ultimate compliment?\n Any compliment from you.",
    "What do you prefer?\n Phone calls.",
    "What's something small that makes you happy?\n Talking with you.",
    "Is there anything you would want as a birthday present?\n Strawberry cake.",
    "What age do you want to live until?\n I want to be immortal."
];