module.exports = [
    "Do you have a favorite type of weather?\n I enjoy sunny and warm weather.",
    "What do you think of it?\n I appreciate the subtle touches of pink.",
    "Do you think we can reclaim the surface?\n I think it's achievable.",
    "do you think Eden has any flaws?\n It's missing a certain warmth.",
    "Is there anything you need?\n I just wanted to chat with you.",
    "There are beautiful white lilies blooming in the patio. We should go check them out later.\n What's the scent of lilies like?",
    "Don't you ever want to sleep in?\n I guess it's because this isn't my home.",
    "I haven't had a nightmare in ages. It feels awful.\n Did you dream about ghosts?",
    "... It's distressing.\n Did you see them off properly?",
    "If I may ask, how do you see them?\n They're my comrades in life and death.",
    "And she's so obedient.\n ...?!",
    "Are you all comfortable?\n It's not ideal, I feel suffocated at times.",
    "How does it feel to carry the hopes of everyone in the Ark?\n It feels like a heavy burden.",
    "That actions have consequences and people who do bad things will eventually get what's coming to them.\n It's hard to say.",
    "Do you think it's fair or unfair?\n It's unfair.",
    "But be careful, she's more dangerous than she seems.\n How so?",
    "I'm interested to hear your perspective.\n It's a good place to live.",
    "I assume it's quite different from the cuisine in the Ark.\n It's a heavenly delight.",
    "Have you ever tried your hand at skinning a deer?\n No, but I have an idea of how it's done.",
    "What's the point of reclaiming the surface?\n All I want is for everyone to be happy.",
];
