module.exports = [
    "I'm thinking of making something similar. What are some special features I should integrate into the design?\n Whenever you sit down, a small electrical current will run through it.",
    "Depending on the temperature and air composition, it can come in different hues.\n I didn't know that.	",
    "who do you think I respect the most?\n BOOM Guy.",
    "Is that what you think, Mr. Commander?\n Is that what you think, Mr. Commander?",
    "Trony chugs them like there's no tomorrow. It can't be good for her health...\n Let's confiscate her stash.",
    "Like clipping through forbidden paths and the like.\n As long as players are having fun, that's what's important, isn't it?	",
    "Give it to me straight.\n That's not even a question. It's BOOM.",
    "Have you ever felt anything like that?\n I have.",
    "If you give it to me, I'll fix it for you in a jiffy.\n Thanks.",
    "Have you ever seen one in real life, Mr. Commander?\n I have.",
    "Give me four words that start with the letter \"E\".\n ElecTronycs, electricity, electrolyte, electromagnetic.",
    "Can you guess why?\n Because it's dry?",
    "Tah-dah! BOOM is officially installed on your shower mirror!\n Now I'll be able to amuse myself while showering.",
    "Directly controlling an energy source invisible to the naked eye, to make it bend to your command...\n So cool!",
    "Electric Shock seems a bit underwhelming.\n I think it sounds cool.",
    "but what do you personally think is its best aspect?\n It's big fun in a small package.",
    "How would you feel?\n If living meant having to accept dirty money, I'd rather die.",
    "what do you think of Trony?\n She's great. Competent and cool.",
    "*Buzzzzz*\n *Zap*",
    "I'm... asking for a friend.\n I'd use what little space was left to install a game with a smaller file size.",
];
