module.exports = [
    "What is your favorite flavor?\nPeach.",
    "Got any tips?\nCome to my office. I can help you.",
    "Am I... short?\nThe shorter, the cuter!",
    "Coach, do you ever get tired of being a Commander?\nAll the time.",
    "I have a big competition tomorrow at Nepenthe.\nI'll be there. I promise.",
    "I wanna know what skateboarders were like back then.\nFree as a bird.",
    "There's a park by the gym.\nSure.",
    "She says I can't have any carbs... and I have to take protein Splendamin four times a day.\nThat sounds like workplace bullying.",
    "I know they're just kids, but they need to learn to think for themselves, right?\nTeenagers only copy the coolest people.",
    "Coach, have you ever... liked someone?\nI'm still waiting.",
    "What do you usually do to pull yourself back up on your feet?\nI face the problem head on until I overcome it.",
    "What do you normally carry in your pockets?\nSome candy or gum.",
    "what's the first thing you would do?\nExperience my first moment of freedom skateboarding with you up on the surface.",
    "What do you think I should call it?\nFirst off, what's the trick?",
    "They're both the same brand.\nOne that's tricked out.",
    "I want to live up to those high expectations, so I always push things to the limit.\nThat mindset is what got you to where you are today.",
    "I know full well she'll smoke me, but I think it'd be fun, don't you?\nIt'll be a race for the ages.",
    "Coach, I need something right away. Can you guess what it is?\nShoes.",
    "You think I should tell Folkwang to give skateboarding a try?\nI think it's a great idea.",
    "You think there's any way to counteract that problem?\nHave everyone wear safety gear."
];