module.exports = [
    "They have no basis in science, but do you believe in ghosts?\n I believe ghosts exist.",
    "Let me know if you're not feeling well. I'll prescribe you some medicine.\n Um... sure. Got it. Don't worry about me.",
    "Sigh...\n Let me guess... You don't feel like buying new ones.",
    "Hmmm...\n I don't want to get on the lab table just yet.",
    "Days like this make me want to turn in my two weeks notice.\n If you quit, think about all the research that will go unfunded.",
    "What are your thoughts on this issue, No. 7?\n Science can help you overcome any deficiency.",
    "Have I been overthinking it?\n Just keep at it, you're bound to come up with a solution sooner or later.",
    "I'll make it for you.\n If you want to give me some medicine, just say so.",
    "Do you think there's any truth to that?\n That's just an old wives' tale.",
    "and now I don't feel like doing much of anything.\n Develop a medication that will give you some energy.",
    "No.7, have you ever been to the Outer Rim?\n Yes.",
    "Is that true?\n ...",
    "No. 7, you know that I think about you a lot, don't you?\n It's only natural to look after your test subjects and make sure they're healthy.",
    "Do you think there's any way to make them less intimidating?\n Tranquilize people before bringing them in.",
    "but I figured you wouldn't want me to. Unless...?\n I think it's a great idea.",
    "Does that kind of story... interest you?\n No.",
    "How would you feel if I used you as a test subject for some dangerous experiments?\n I don't believe you'd do something like that.",
    "Do you know that phrase?\n Yes, I do.",
    "Do you like me calling you No. 7?\n I like it.",
    "No. 7, which flavor do you prefer: strawberry or orange?\n Orange.",
];
