module.exports = [
    "Tired now. Sleep.\nYou're tired because you sleep too much.",
    "Which?\nSandwich.",
    "More?\nKeep it coming until there's more cream than coffee.",
    "Instead?\nYou need to do your own work.",
    "Want... nice place.\nJust sleep here.",
    "Annoyed.\nBut you'd be bored without them.",
    "Bothersome.\nBut you'll do it because you enjoy it, right?",
    "Music. Recommend?\nNo music. Noise canceling headphones instead.",
    "Good? Bad?\nI'm not sure. I think you look kinda cute when you're asleep.",
    "Nightmare. Terrible.\nBut you could sleep on literally anything, right?",
    "Don't understand.\nI'm sure Cream Coffee will sell better next week.",
    "How to use?\nThey'll go towards renovating some facilities in the Outpost.",
    "What now?\nTry counting sheep.",
    "Difficult. Annoying.\nLet them have it next time.",
    "Why?\nIt's because of the economic recession.",
    "Boss. Scary.\nBothersome?",
    "How?\nSleep more and cut back on your spending.",
    "...\nDo you not want to talk since you don't feel well?",
    "Raining. Can do what?\nHead back to bed.",
    "Which?\nA nice and soft sofa is the only way to go."
];