module.exports = [
    "Ugh, I'm hopeless.\n Was the test really difficult?",
    "Huh? Who?\n Me.",
    "I'm not so sure myself.\n You're good at piloting T.A.L.O.S.",
    "I-I was just curious...\n Because I care for the people I surround myself with.",
    "T.A.L.O.S. is nowhere to be seen.\n Looks like it'll be just you and me today. How intimate.",
    "Shall I wake her up?\n No, I'll wait for her to wake up.",
    "I don't know why, but that makes me feel kinda weird...\n You are both your own individual people.",
    "what do you think is the most important trait a pilot should possess?\n Objectivity and quick decision-making.",
    "and T.A.L.O.S. passed with flying colors.\n Wow, that's incredible.",
    "have you ever encountered a Pilgrim by any chance?\n Yes.",
    "do you prefer cloudy or clear weather?\n Clear days.",
    "what do you do?\n I think of the times I did well and try not to be too hard on myself.",
    "That's been on my mind quite a lot.\n It will happen to you someday.",
    "what kind of personality would mesh well with mine?	\n Someone reliable and assertive.	",
    "I could replace it for you if you'd like.	\n How would you do that?	",
    "How does T.A.L.O.S. look today?	\n Hmm... It seems shinier.	",
    "but I don't know what I should do.	\n What about just resting?	",
    "T.A.L.O.S. is capable of all sorts of things, so let's see what it can do.	\n T.A.L.O.S., sing a song.	",
    "how should I act?	\n Be careful not to act too impetuously, so as not to arouse suspicion.",
];
