module.exports = [
    "Graul.\n Would you like to sleep in the Commander's Room?",
    "I bought a scarf from the store.\n Did you buy it for Timi?",
    "What's your takeaway from that?\n Surviving in the wild isn't easy.",
    "Living together in the same space, going out on walks, giving them treats, and all that.\n I think it would be hard.",
    "When you grill meat, how do you like to cook it?\n Rare.",
    "Do you know anyone like that?\n Me.",
    "What should I do to get over that?\n Talk to me whenever you're feeling tired.",
    "Some students came to volunteer at the shelter, and I overheard one of them say that about Timi.\n I think that saying could apply to you as well, Leona.",
    "Bears can be such ferocious creatures, but they're oftentimes viewed as cute and cuddly.\n That's because bears are cute.",
    "How many teeth does an adult lion have?\n Around 30.",
    "What are you looking at me like that for, Zoo Keeper?\n Because you're so beautiful.",
    "Would you like to try?\n Poke Timi's paw.",
    "I could probably knit a blanket with all the fur he's lost.\n It's shedding season, so these things are inevitable.",
    "G-Grrr...?\n They are a member of the cat family, after all.",
    "Do you remember what I like?\n Meat.",
    "Animals were kept there, and people paid money to go see them.\n I feel sorry for the animals.",
    "Am I really that intimidating?\n It's not you, but rather the animals that you always have around you.",
    "What do you think I can do to make people realize how charming he can be?\n Promote the shelter volunteer program more heavily.",
    "and Timi goes...\n Graul!",    
];
