module.exports = [
    "What do you think would look best?\n How about some cute animal pajamas?",
    "When you were a student there, what expectations did you have of your instructors?\n I would have killed to have someone like you there.",
    "Is there a location you would recommend?\n How about the animal shelter run by Happy Zoo?",
    "I just got a reply saying that if I want any changes made, I'll have to do them myself.\n They clearly trust you.",
    "I don't look like a fox, do I?\n Sure you do. Foxes are intelligent as well as easy on the eyes.",
    "The interface is totally different from the last version.\n I can help you familiarize yourself with it.",
    "*Whirrrrr*\n That drone sounds kinda cute when it's whizzing about.",
    "but it feels like the data sync speed for T.Va. has been awfully sluggish lately.\n Put a blanket over Marciana's stomach.",
    "what do you think a good teacher should be like?\n Someone who recognizes the students for who they are, and helps them move towards a brighter future.",
    "I'm trying to think about how I should handle this.\n Is there any way to encourage them to fly their drones outside?",
    "It's a layered dessert made with a variety of fruit, fresh cream, and custard.\n I have, but I've never tried it. Do you want to go try some together?",
    "I'm not sure how they got here, but there's a big pile of dolls lying on your desk.\n Neon won a bunch of them at a claw machine, so she must have left a few there. Do you want one?",
    "What should I say to help out?\n Compliment her and say that she's been doing well.",
    "What should I do with them?\n How about giving them to the students?",
    "It's a cake with a topper of a fox hugging a penguin.\n Awwww so cute!",
    "How do you get the most out of your designated rest times?\n Bring my hands up and cover Marciana's eyes.",
    "will negatively affect my students.\n You're always doing your best, and that's all you can do.",
    "What does it mean to be hip?\n When you're unique and novel in your look or demeanor.",
    "Do I look angry to you right now?\n Yes. Is there something wrong?",
    "This is a drawing Rei gave me.\n It's cute. She's a talented artist.",
];
