module.exports = [
    "What's he like anyway?\n He's definitely worthy of respect.",
    "and she just bumps her head against the cabin wall to fix it. It's like it gets magically repaired or something.\n I thought radars were supposed to have precise components?",
    "Mast seems to have a lot on her mind.\n Wait patiently.",
    "So who do you want to compete with the most, Captain?\n The humans' enemy, Rapture Queen.",
    "But it's stuck dry-docked most of the time.\n That's why we're always stoked when an opportunity comes around.",
    "Like, when we were cleaning, out of nowhere, she just yells, \"Starfish!\" What\'s up with that?\n Maybe that\'s Anchor\'s special code system.",
    "Do you have any animals that you trust, Captain?\n I think a parrot is best for a pirate.",
    "Are there any legends or mysterious phenomena that you've always wanted to experience first-hand?\n I want to explore the Devil's Triangle.",
    "So, what do you think mine would be?\n The Last Voyager.",
    "Was it for the thrill of adventure, the money, or your crewmates?\n I wanted to see new places I've never seen before.",
    "Captain, do you think I can become a pirate?\n Whether or not they can achieve it, a true pirate chases their dream, isn't it?",
    "What do you think he wants?\n Maybe you haven't been playing with him enough?",
    "We'll enjoy the pirates' feast until Captain comes♪\n Hahaha! Let's set sail and go on an adventure!",
    "Do you wanna be my crewmate?\n Aren't we already crewmates?",
    "When do you think rum tastes the absolute best?\n When I'm drinking it with Helm.",
    "It's hard to gauge, you know?\n Did Morgan learn new phrases?",
    "Have you ever heard of the drifting ghost ship?\n Tell me about it.",
    "With that kind of resilience, it could probably beat a sea monster easily.\n You're pretty impressive for being able to handle it.",
    "What do you think, should we get a cat for the Admire?\n Maybe we can ask Nero to help us out.",
];
