module.exports = [
    "or always daytime?\n Always nighttime.",
    "Is it really that important that I have a hobby?\n I'm sure we can figure something out together.",
    "This is the first time in ages I've had some time to myself. What should I do?\n Want to hang out?",
    "What kind of firework should we make?\n Something nice and loud.",
    "Are all adults like you?\n I'm afraid not.",
    "Do you think she'll still be friends with me then?\n I'll be there for you as well.",
    "I want to go!\n Next time, I'll take you and Belorta.",
    "What if it comes out again tonight? I don't think I can sleep.\n I'll stay with you until you fall asleep.",
    "She also said to keep it a secret, so no blabbing about it!\n Can't wait to try it.",
    "What's the deal?\n You have feelings for them.",
    "Do you think nobody likes toys anymore?\n Maybe they're just afraid of getting pranked.",
    "What should I yell back at her?\n Firecracker!",
    "What's the one thing you are most scared of?\n Belorta.",
    "Old-Timer, what do you do when you're sad?\n I cry like a little baby.",
    "If I'm smart, no one will be able to prank me! Right?\n You're probably right.",
    "So... if you don't, then you can't become an adult, right?\n Exactly.",
    "Why do you think she was so upset?\n Because there was nothing left for her to eat.",
    "who do you like more?\n You.",
    "so, what should I get in return?\n A \"No Teasing for a Day\" voucher.",
    "What can I do to make her stop?\n You should tease her back.",
];
