module.exports = [
    "Maybe she doesn't know my name?\nShe's just a nut for firepower.",
    "So... does everything in the fridge belong to Anis?\nYes.",
    "Is she sick or something?\nMaybe her head hurts.",
    "Did I... fail to protect you before?\nThis time, I'll protect you.",
    "What should I say to her?\nCover her in bandages.",
    "Commander, do you hurt anywhere?\nMy leg has been hurting since last night.",
    "Commander, what's your favorite place to be?\nIn the Commander's room along with you.",
    "Commander, which flavor do you prefer? Grape or apple?\nApple.",
    "Commander, what type person do you like?\nThe person in front of me.",
    "A blue sky, or the night sky?\nBlue.",
    "Would you like to join us?\n...",
    "Commander, you should turn back.\n... Rapi?",
    "Commander, could I have that pen that you're using?\nSure, I don't need it.",
    "In the dream, you were pointing a gun at me.\nThen what happened?",
    "Have you ever seen a mermaid?\nNo.",
    "Do you listen to any songs before you go to sleep?\nThe same song.",
    "Scissor!\nShow scissors.",
    "I'm happy to be talking with you right now!\nMe too.",
    "Rapi came in first, but I was second!\nTry and finish on top next time.",
    "and then open it, it gushes out like a fountain!\nHow do you know that?"
];