module.exports = [
    "but he always says his brain is his weapon of choice, not his brawn.\n You need to give him a proper reason to want to see a fight.",
    "if I weren't the head of the Peony Association.\n A policewoman.",
    "What kind of alcohol do you like?\n Cocktails that are on the sweet side.",
    "How do you like my sunglasses?\n Where did you buy them? I want a pair.",
    "what's your stance on white lies?\n I think they're just as bad as any other type of lie.",
    "Is there any way you could teach me how to save money?\n I'm not really good at saving money myself.",
    "I think you're the most beautiful person I've ever known.\n Right back at you.",
    "Loyalty! Loyalty! Loyalty!\n Loyalty! Loyalty! Loyalty!",
    "As I enter the Commander's Room huffing and puffing, Moran doesn't seem to notice my presence.\n Got something on your mind?",
    "when it comes to girls, do you have a type?\n Someone who's cheerful.",
    "Do you have suggestions?\n Arrange a get-together for the squad.",
    "I thought they might look nice in your room.\n Peonies are my favorite flower.",
    "what do you usually do when you're sad?\n What makes you ask? Are you feeling sad?",
    "Have you ever been on a date?\n We can go on one together after this session.",
    "I'm not sick, am I?\n You like me, don't you?",
    "You don't think that, do you, Cadet?\n I'd say you're more innocent than ignorant.",
    "Do you have any recommendations?\n Maybe they're busy.",
    "What do you value most in life?\n Loyalty.",
    "I'll protect you no matter what happens.\n You're the best.",    
];
