module.exports = [
    "Who do you think gave them to me?\n Maybe you slept in someone else's clothing?",
    "If you do, can you tell me about it and no one else?\n Actually, I can't eat hot croquettes because they're too spicy.",
    "How can I build up more memories?\n Even now you're making future memories.",
    "They really were like a carbon copy of me.\n That's very interesting.",
    "Are you a celebrity or something?\n A-lister. I've even been on TV a few times.",
    "I can't wait!\n Can I tag along?",
    "What could have happened?\n There's someone out there with the same name as you.",
    "Can I, teacher? Can I?\n We'll go after we're done talking.",
    "So, what are we supposed to talk about?\n Anything you want.",
    "I'd love to hear your recommendations.\n Hum the tune for her.",
    "Do you think I'll ever be part of a squad like that one day?\n We already are a squad.",
    "And they also have a croquette store!\n Do you want to go together?",
    "I felt so bad for them both.\n What's so sad about it?",
    "But, I've never seen them before in my life!\n Maybe you've got an irresistible star quality to you.",
    "As for me, I'm gonna let myself get caught in the rain. I've never been drenched by the rain before!\n You'll catch a cold.",
    "And I want to see the ocean!\n Okay. Let's go together sometime soon.",
    "Wait, have I ever tried jalapeño croquettes before?\n How could you have? They were only added to the menu today.",
    "Do... do you think I did something wrong?\n No. I'm sure they were just mistaken.",
    "D-do you think there's something wrong with me?\n Let me feel your forehead.",
    "What are you in the mood for?\n Mild croquettes.",
];
