module.exports = [
    "... How exactly is it unique?\nIt looks like a firework going off mid-explosion.",
    "How strong do I look to you?\nYou've got a clear weakness, so I don't feel you're all that strong.",
    "*Sigh*...\nYou seem stressed.",
    "Besides, what reason would I have to eat with you of all people?\nFair point.",
    "Have you always had a such flagrant disregard for your own well-being?\nKinda.",
    "What are you starting at?\nI was admiring your face.",
    "Fine, you get to ask one question. And make it quick.\nOn second thought, I'll come back when you're feeling better.",
    "What kind of thing did you think I'd do in my spare time?\n... Exercise?",
    "Got any ideas how I can release some tension?\nLet's do some breathing exercises.",
    "Either of the two.\nMaybe both of us would be here.",
    "Human, how do you like it?\n... Well-done?",
    "What do I need to burn?\nI just need a small fire to cook some food.",
    "What's the secret? Does it really amount to just sticking close to you?\nMy devilish good looks.",
    "I don't think I've ever thought about it.\nOr someone who needs protecting?",
    "From what I hear, the Ark is perfectly livable.\nIt gives us the strength to go on.",
    "Why should I tell you anything?\nSomething tells me you two aren't on good terms.",
    "Are you genuinely curious about what I do up on the surface?\nIt's not often I get to talk to someone who spends most of their time up on the surface.",
    "Who is that?\nThe commander who was at Eden.",
    "What is this?\nWant some?",
    "How would that change anything?\nMaybe the situation wouldn't be as dire as it is.",
];