module.exports = [
    "Would you like to try?\n Draw once.",
    "Something less formal.\n A swimsuit.",
    "What should I do?\n You're twins. You two are very similar.",
    "do you prefer curvier girls, or slimmer girls?\n I like both.",
    "Can I share my luck with you?\n Hold out my hand.",
    "did you come to Coin Rush yesterday?\n Yes, I did.",
    "I... I...\n Wait until Noir finishes talking.",
    "Do you think I should get it trimmed?\n How about tying it up?",
    "I'm always cripplingly shy whenever I meet people for the first time.\n Find a topic that you're both interested in.",
    "And rabbits go...\n ... \"Goo goo gah gah\"?",
    "I've got pole dancing practice today, so I've got to leave early.\n No problem, we can reschedule for another time.",
    "Are there any things that you consider to be bad luck?\n I'm only unlucky that I don't get to see you every day.",
    "I've seen the photos. They're so adorable!\n Yes, I have.",
    "But what if something unfortunate happens to me?\n Then you'll be downgraded to a semi-lucky bunny.",
    "I've been having a hard time with it recently.\n The exquisite postures and technique.",
    "Have you ever heard of the carrot song?\n What is that?",
    "How can I get over it?\n Think about Blanc.",
    "will you be coming to the show tonight?\n Sorry, I don't have time.",
    "It's really embarrassing... why do you think they do that?\n Because you're so pretty.",
    "How do you think Blanc manages to be so charming all the time?\n Because of her lively personality.",
];