module.exports = [
    "Do you think they have any real meaning?\n I think their value is limited.",
    "like this cassette player, for instance?\n I think they're cool.",
    "Long time no see.\n Red Hood, are you trying to sound like Rapi?",
    "but Dorothy had a cute side to her as well.\n Quit pulling my leg.",
    "It's white and supple, and feels tender to the touch.\n Snow?",
    "I'm already reminded of Scarlet and Dorothy as they used to be.\n Did they fight a lot?",
    "Don't you agree?\n I prefer vinyl records.",
    "You wanna know what the first book I gave Rapunzel was called?\n Eager & Insatiable.",
    "guess who made this weapon I'm using?\n Snow White?",
    "doesn't step out of line.\n I'll do my best to persuade her whenever I can.",
    "Do you ask a different Nikke out every day?\n 	Not necessarily.",
    "Is she still as adorable as before?\n Utterly irresistible.",
    "is our favorite swordsman still living life to the hilt?\n Very much so, all with the help of alcohol.",
    "Is Rapunzel still fixated on... you know what?\n More than ever.",
    "It's a strange thought, and whenever it pops up in my mind, I'm a bit unsettled.\n I think that's a perfectly normal reaction.",
    "What do you think is the most important quality of a good Commander?\n A sense of humor, I guess?",
    "Waddya say you and I get frisky?\n Er, isn't that a bit...",
    "I kinda miss...\n Me?",
    "the past or the future?\n The future.",
    "Da dada♪\n Hum along to the song with Red Hood.",
];