module.exports = [
    "Why do you▣▣ insist on putting▣▣ this convertor on me?\nBecause I'm not confident that I can restrain you if I have to.",
    "▣I had so much fun cutting□□ it up with the Nikkes here yesterday, I had※▣tears coming down my face.\nI'm glad to hear that you've managed to adjust.",
    "If you rescued a ※※kid who was about to drown ▣▣※and they said afterwards that they wanted some Nutrium□, what would you do?\nI'd probably buy them some.",
    "□※S is standing pretty at 30 points, R is at minus 6□▣points, E is....\nAre you calculating points?",
    "Everyone▣can't stop□□complimenting you.※▣※\nHow does that make you feel?",
    "Ever since I was released□※from the rehabilitation center ▣※, I've been wanting to do something that has meaning.\nOkay, let's go together during the weekend.",
    "□※Every time I think back on ▣※□what you did, I bust out※□laughing.\nLast week? Wait, you mean when I...?!",
    "※※I don't mind□it, but security▣here is□ so lax.\nQuency never was one to follow the rules.",
    "I've already been□□rehabilitated.\nShould we do something else then?",
    "□▣If you could commit one sin,▣※what would it be?\nOffer a live sacrifice to appease the gods.",
    "※▣Would you prefer to be given a ▣※ bar of Splendamin, or a ▣※□light croquette?\nSplendamin.",
    "※I'm▣□▣bored out of my gourd.\nShould I give you a piggyback ride?",
    "※Do you※▣think▣※□that's true?\nI agree somewhat.",
    "※▣From what I□hear※▣you're close to□everyone.\n... You?",
    "□▣Then▣※I wouldn't feel□misunderstood▣※※.\nI like it when I can see your face.",
    "Or a wide circle※□of acquaintances▣▣?\nA wide circle of acquaintances.",
    "▣□▣but it feels like everyone※□is always▣judging me▣.\nButter them up first with a bar of Splendamin.",
    "How▣▣can I□※get her□▣※to not be mad at me anymore?\nNothing you can do. Just have to wait until she cools off.",
    "※□Quency▣is too busy, □※※so I don't want to bother her, and Guilty※could crush me like a bug▣if I rub her the wrong way.\nI'll blend your food up for you.",
    "Gu▣ilty says※there's nothing she despises more than▣※falsehoods.\nLying is also a skill."
];