module.exports = [
    "Pretty cool, huh?\n Where did you get that snow?",
    "Do you prefer strong scents or something more subtle?\n Subtle.",
    "When I saw her appear on the horizon, she seemed like a true Snow Queen!\n You must've been frightened losing your way. Try not to stray off too far in the future.",
    "They're both so kind, and beautiful, and get along so well.\n Honestly, I'm more happy when I'm spending time with you and Belorta.",
    "Or maybe it was Emma?\n It definitely wasn't Emma.",
    "Belorta always aims for the face, so it's hard to beat her.\n Try using some unique weaponry.",
    "Mica hands over a small snowman.\n Thank you. Did you make this yourself?",
    "I think I look kind of weird without applying camo cream.\n You're naturally cute, so any look you adopt is fine.",
    "Servant, what do you typically associate with a hot spring?\n You, Ludmilla.",
    "which really hampers my cleaning.\n Use a ribbon to secure Mica's sleeves.",
    "What do you think would be a great gift?\n Why don't you discuss it with Belorta?",
    "but I wasn't able to taste anything!\n Were you eating Emma's cooking?",
    "Which one do you like, Old-Timer?\n Hmm... I like this star-shaped firework.",
    "I never expected I'd get to see so much snow on the surface in my life.\n Sometimes I feel that way too.",
    "do you think I look good in this outfit?\n Yeah, it suits you.",
    "Mica opens her hands to reveal a small pile of stones of various shapes.\n They're so pretty. Like little gemstones.",
    "What do you think that is?\n Because we get to be here with the people we love?",
    "Do you enjoy it as well, Old-Timer?\n It's the best. I try and go whenever I have the chance.",
    "How was that greeting?\n I like the energy that you're bringing to it.",
    "Where is your favorite spot in Snowfield?\n The breathtaking waterfall.",
    "and you're always filled with a sense of pride once you're done cleaning.\n Looks like you might have a lot on your plate. Do you want some help?",
];