module.exports = [
    "I screwed up again today.\nIt's okay. Everyone makes mistakes.",
    "Clean clean, squeaky clean!\nWant to clean together?",
    "Do you prefer sunny or rainy days?\nI like sunny days.",
    "I broke a glass while I was cleaning today.\nWere you hurt?",
    "Maybe even more than cleaning.\nI prefer you over cleaning as well, Soda.",
    "Do you think we should start with the kitchen or the lobby?\nThe kitchen.",
    "What's your favorite food? Tell me and I'll make it for you.\nAnything you make is my favorite.",
    "Would you like a massage?\nIf it's not too much trouble...",
    "What should I draw?\nYour face.",
    "Soda is cleaning every nook and cranny of the Commander's Room.\nIs something on your mind?",
    "Do you have any suggestions?\nTry and make your eyes twinkle.",
    "Guess what the lyrics are after that!\nMeet your special maid!♪",
    "Guess what she said.\nThat you were the best cook around.",
    "Is there anything you'd like to see me in other than a maid outfit?\nIt'd be interesting to see you in some casual clothes.",
    "But all I ever seem to do is make mistakes. I'm so sad...\nThat's what makes you so endearing, Soda.",
    "Nice to have you back, Master!\n... Hello.",
    "But I've already bought a lot of cleaning tools... What should I do?\nConsider it an investment towards your own happiness. Go for it.",
    "By the magic invested in me, I command you to be delicious! Moe moe kyun!\nAlakazam!",
    "You can choose your own theme.\nThe climactic scene of a romantic-comedy.",
    "Did you see what it was?\nA heart."
];