module.exports = [
    "which one do you think is better suited as a punishment in a game?\n Splendamin.",
    "What genre of music do you like?\n The sound of nature.",
    "Sometimes I would like to experience a new environment.\n What about going to the desert?",
    "They might have even been a super rookie like me? Hehe.\n They might have been more sloppy than you think.",
    "What does it feel like to like someone?\n Like feeling you could survive any extreme situation with that person.",
    "Is there any special method of survival?\n It's about utilizing the resources that you have. No matter how scarce they are.",
    "I know it can't be helped but it still lingers in my heart... What should I do?\n Instead of those you couldn’t rescue, you should think about the ones you did.",
    "My goal is all about survival. About continuing to live as long as I can.\n Survival is also my goal.",
    "if the two of us fought, who do you think would win?\n You, of course.",
    "but what do you think I would be doing if I wasn't a survival expert?\n Firefighter.",
    "Is there any way I can become more like Alice?\n You are fine just the way you are.",
    "How are you so good at eating unusual foods?\n I learned from the master of the wild.",
    "but when I actually find myself in a survival situation, it doesn't go as smoothly as I imagined.\n You just need to keep practicing.",
    "What would you think if I tried making survival videos like them?\n I don't think there are any shows with a similar concept so I think it would work well.",
    "So, don't you think we can use that against the Raptures?\n Why didn't we think of that before?",
    "But, someone was already inside!\n Don't tell me it was... a bear?",
    "So I gathered some, which do you think I should take?\n Some unknown plant roots.",
    "Do you have any good ideas?\n A pillow that guarantees a good night's sleep anywhere.",
    "I'll eat one and give one to you. Now, pick one!\n Pick the bag that is wriggling.",
    "When will I ever be able to find a cameraman like that?\n I can do it when I retire.",
];