module.exports = [
    "What's your favorite food, Commander?\n Instant food that can be easily consumed.	",
    "Where do you like to go to on your day off, Commander?\n My room.	",
    "Should the bug be fixed?\n Still, it should be fixed.",
    "Commander, why do we have to write reports every day?\n I'd like to know that, too.",
    "How do I even do that?\n Just hold the trash can and put everything you pick up inside.",
    "Who's your favorite Ark Ranger, Commander?\n Romantic Black Ranger.",
    "What's the surface like for you, Commander?\n A beautiful place.",
    "Do you like puzzle games, Commander?\n Yeah, I like them.",
    "Commander... what should I do now...?\n Let's take this opportunity to promote the Ark Ranger.",
    "do you tend to use the same one?\n Yeah, it's too much hassle to come up with new ones.",
    "Do you, um, know how it's generated?\n Isn't it made by running a generator?",
    "when making instant noodles?\n Isn't it best to follow the instructions on the packaging?",
    "What do you think of Elegg?\n She is competent and takes good care of those around her.",
    "Is walking considered an exercise?	\n Of course, it is.",
    "our squad name sounds weird?\n Electric Shock sounds cool.",
    "Trony glances at me silently.\n Trony, what's going on?",
    "Ugh... Isn't that too much...?\n How about hiding it secretly from now on?",
    "You can just pretend you didn't hear that...\n Reclaim the surface.",
    "Do you like days like this, Commander?\n Yeah, I do.",    
    "Trony hides two gamepads behind her back.\n Hey, are you still there?",
];
