module.exports = [
    "How do you usually spend Christmas?\n I often go out to Royal Road.",
    "I now understand why Mighty Tools makes this their life's work.\n I still think being a queen suits you best.",
    "Running Snowfield Hot Spring is no easy task.\n You've got to stay strong.",
    "or with others?\n I prefer traveling with others.",
    "Servant?\n It's gorgeous.",
    "Do you prefer cooking or eating?\n Cooking.",
    "did you feel that anything was lacking during your stay at Snowfield?\n There could have been a greater variety of dishes...",
    "What gift would you like, Servant?\n You.",
    "Servant, what do you typically associate with a hot spring?\n You, Ludmilla.",
    "Do you have a fascination with these kinds of ghost stories?\n Wait... are those handprints I see outside the window?",
    "Which sections did you find most interesting, Servant?\n The hot spring's history.",
    "How about it? Would you like to try our breakfast?\n Of course. Can I have some now?",
    "What should I do?\n Sit beside her.",
    "Do you have a particular fondness for any?\n Cake.",
    "Is there anywhere you'd like to go in particular?\n The forest next to the hot spring.",
    "What do you think?\n We should remind everyone of this beforehand so nothing like that happens.",
    "Today, I would like to drink tea that fits thematically with the hot spring.\n Prepare green tea.",
    "Do you know the rules of which I speak, Servant?\n Before entering the hot spring, you should wash your body.",
    "Servant.\n Prepare to go out with the shovel in hand.",
    "I don't have to worry about my hands wreaking havoc on the place.\n I'm actually a little bummed now that I have less work to do.",
];