module.exports = [
    "What catchphrase should we use to hook people in?\n Get the latest holiday fashions for you and your loved ones.",
    "It's been days since my last livestream...\n I know it's hard. Let me give you a massage.",
    "but I'm not sure what kind of party it should be.\n A casual get-together with your fans and other livestreamers.",
    "A wedding on a snowy day... Isn't it romantic?\n Would you like to rehearse?",
    "When do you find me most appealing?\n When you're out on a date.",
    "*Yawn*\n How can shopping make you tired?",
    "I'm sure we'll be able to find something in the Ark.\n I think a place just opened up that sells truffle soup.",
    "I'm fine with it, but what about you? Aren't you freezing?\n It's okay. You can hold my hand.",
    "Do you have any vacation plans?\n None. Help me plan something.",
    "How old were you when you stopped believing in Santa Claus?\n I never stopped believing in Santa.",
    "White or black?\n White, obviously.",
    "I'm in a good mood today.\n I'm enjoying spending time with you too.",
    "I always end up thinking of a special someone.\n I'm the same way.",
    "but I already bought so many. There's barely enough room left on the tree.\n Then let's buy another tree.",
    "How about we go shopping when we're done talking?\n Sure, we can buy some winter clothes.",
    "Is there any way we can promote them better?\n Wear them in your next video.",
    "Sometimes I think about how nice it'd be if I were like that.\n I like you just the way you are.",
    "I'll hand it over to Sweetie to explain the rest.\n Talk about the importance of Nikkes and their mental health.",
    "One, two...\n Nikke!",
    "What's a good way to ring in the New Year?\n Going on a date with your loved one.",
];