module.exports = [
    "The only thing is that I can't seem to jump very high.\n That's because it's still early in your practice.",
    "what flavor of carrot could you really go for right now?\n A cotton candy-flavored carrot.",
    "Do you feel that way too, Rabbity?\n Nope, snowflakes sparkle more.",
    "Oh yes! Would you like to have a listen?\n Certainement, I'd like to listen.	",
    "Am I doing a good job sweeping?\n Are you interested in being a maid sometime?",
    "What do you think it would be like if my Queen becomes a rabbit as well?\n Then she'd become Snow Queen Bunny.",
    "I bet you won't even feel a thing when she gives you the injection!\n You're right. It doesn't hurt at all.",
    "Maybe that's why they're lucky rabbits!\n I feel happier whenever I see you too.",
    "what do you think the Queen is doing right now?\n Thinking about you.",
    "What do you think it means?\n An auspicious dream.",
    "What do you think would make her happy?\n The luck of a rabbit.",
    "How many coins do you think are in here?\n Two?",
    "Since I've become a rabbit, do you wanna have a race?\n I'll take you on.",
    "why is Slippery Bunny always leaking water?\n She's actually the Water Queen.",
    "I really like you!\n I like you too.",
    "What should I eat when I go there?\n Carrot cake.",
    "I've been dazzled by all the sparkly things!\n The North is full of sparkly things too. The snow, for one.",
    "but I guess that's not possible, huh?\n You can invite her to come over wherever you're living.",
    "What do you think would be good?\n Some cotton candy in the shape of a rabbit.",
    "There are so many rabbits here, I'm so happy!\n I'm happy too, because you're here.",
];