module.exports = [
    "Is she sick of me or something?\nUse physical force to keep her with you.",
    "but I don't have enough money to get both!\nTie Mihara up with the whip.",
    "Commander, do you know what happens to a Rapture once it's captured?\n... They probably get disposed of.",
    "Why? I'm much better with a whip than a gun.\nBecause Raptures don't feel any pain.",
    "Is there anything I can do to change my sleeping habits?\nFind something to hold onto before you go to sleep.",
    "what should I do? I certainly won't be able to capture Raptures anymore.\nJust live out your days in peace.",
    "But what's the point of tying a knot if you don't make it tight?\nYou should tie Mihara up, too.",
    "How would you feel if someone suddenly hit you, out of the blue?\nOne-sided violence is never good.",
    "Should I buy a new pair?\nIs it really that big a deal that the handcuffs are broken?",
    "A hit to the shins? A punch to the gut? Stubbing your toe?\nI haven't been hit that much, so I really can't say.",
    "What would you say is my strong suit?\nYou're pure of heart, and kind.",
    "What does it taste like?\nWhen you're a little older, we can go try a few together.",
    "means the world to me.\nI'm sure Mihara likes you as well.",
    "I'd prefer to be alone today.\nCaress her hair.",
    "I'm not bothering you by talking to you every day, am I?\nYou've never bothered me, not even once.",
    "I want to show you something fun.\nYou reach out your hand.",
    "Do I really have to go?\nIt's important to read up on things you're learning as well.",
    "Do you like me?\nYes, I do.",
    "I'm so exhausted...\nDo you want to sleep here?",
    "Commander, when are you most happy?\nWhen I'm spending time with you."
];